### ISSUE TITLE
Unwanted trail on HSCROLL RIGHT (cpc)

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#1063]
That's excellent, thanks!

I'm just wondering about HSCROLL RIGHT though.

	BITMAP ENABLE(160,200,16)
	BORDER GREY
	CLS BLACK
	DEFINE KEYBOARD ASYNC

	PRINT "12345"
	PRINT "23451"
	PRINT "34512"
	PRINT "45123"
	PRINT "51234"
	CUP
	CUP
	CUP

	FOR i=0 TO 10
	HSCROLL LEFT
	WAIT 100 MS
	NEXT i

	CDOWN

	FOR i=0 TO 10
	HSCROLL RIGHT
	WAIT 100 MS
	NEXT i

Causes this:

![image](https://github.com/user-attachments/assets/56d06c57-bf49-4075-b2a7-bbc8c1d18374)

The 4th line is scrolled to the right, and leaves a trail behind.
I understand if this is intentional, I'm just curious.

HSCROLL SCREEN RIGHT also leaves a trail behind.
Is this intentional?

	BITMAP ENABLE(160,200,16)
	BORDER GREY
	CLS BLACK
	DEFINE KEYBOARD ASYNC

	PRINT "12345"
	PRINT "23451"
	PRINT "34512"
	PRINT "45123"
	PRINT "51234"

	FOR i=0 TO 10
	HSCROLL SCREEN RIGHT
	NEXT i

![image](https://github.com/user-attachments/assets/a1bd2753-c494-4fe0-bc2a-b5585400dfe2)

_Originally posted by @poppichicken in https://github.com/spotlessmind1975/ugbasic/issues/1051#issuecomment-2509685762_

**Comment by poppichicken** [comment]
hi Marco.
The first example (where a single line is scrolled right) works really well now.
However the 2nd example still leaves a trail.
Is this intentional?

	BITMAP ENABLE(160,200,16)
	BORDER GREY
	CLS BLACK
	DEFINE KEYBOARD ASYNC

	PRINT "12345"
	PRINT "23451"
	PRINT "34512"
	PRINT "45123"
	PRINT "51234"

	FOR i=0 TO 10
	HSCROLL SCREEN RIGHT
	NEXT i

![image](https://github.com/user-attachments/assets/f28f999e-4f5b-4426-ba0c-421355631e5f)

**Comment by poppichicken** [comment]
That works nicely now.
