### ISSUE TITLE
Add support for TRS-80 Color Computer

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#124]
The RadioShack TRS-80 Color Computer, later marketed as the Tandy Color Computer and sometimes nicknamed the CoCo, is a line of home computers developed and sold by Tandy Corporation. Despite sharing a name with the earlier TRS-80, the Color Computer is a completely different, incompatible system and a radical departure in technology with its Motorola 6809E processor rather than a Zilog Z80.

EMULATOR: http://www.6809.org.uk/xroar/
INFORMATIONS: https://colorcomputerarchive.com/repo/Documents/Books/ColorComputerMemoryMap.pdf

**Comment by HomerKH19** [comment]
A great goal.
