### ISSUE TITLE
Invalid OPCODE

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#168]
https://github.com/spotlessmind1975/ugbasic/blob/d0e5d1a9966e8d06a44b4d7fd1d34a596507af37/ugbc/src/hw/6809.c#L758

`EOR #$FF` is not a valid mc6809 opcode. You surely mean `EORA #$FF`, but in this case consider a simple `COMA`. But since this is followed by a `ADDA #1`, this whole code results to a simple `NEGA`.

**Comment by spotlessmind1975** [comment]
Optimization done by peepline optimizator.
