### ISSUE TITLE
PC128OP CIRCLE: Garbage pixel on Screen mode #3

### ISSUE THREAD

**Issue by dinoflorenzi** [spotlessmind1975/ugbasic#182]
After color 3.
https://user-images.githubusercontent.com/57636882/139490687-ce3a00c0-a09a-48dd-948d-077acc5e64e1.mp4

**Comment by dinoflorenzi** [comment]
Garbage pixel issue seems to be solved.
![image](https://user-images.githubusercontent.com/57636882/142735781-4d72c5c4-3913-4a91-88c7-3675cb397fbe.png)

**Comment by spotlessmind1975** [comment]
@dinoflorenzi **that good news!!**

I'm only sorry for the black vertical line ... I hope to be able to solve it soon, it's the only thing I have left to solve.
