### ISSUE TITLE
border color for mo5 and pc128op

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#186]
https://github.com/spotlessmind1975/ugbasic/blob/7f834ed5e1f63a3c6e8a2ef1607e82071354adfc/ugbc/src/targets/mo5/color_border.c#L68

These uses ROM api, but works both on MO5 and PC128op.

```
void color_border( Environment * _environment, int _color ) {
	char color[MAX_TEMPORARY_STORAGE]; sprintf(color, "#$%2.2x", (_color&15)+0x60);
	outline0("LDB #$1B");
	outline0("SWI");
	outline0("FCB $02");
	outline1("LDB %s", color);
	outline0("SWI");
	outline0("FCB $02");
}

void color_border_var( Environment * _environment, char * _color ) {
	Variable * color = variable_retrieve( _environment, _color );
    outline0("LDB #$1B");
	outline0("SWI");
	outline0("FCB $02");
	outline1("LDB %s", color->realName);
	outline0("ANDB #$0F");
	outline0("ORB #$60");
	outline0("SWI");
	outline0("FCB $02");
}

```

**Comment by dinoflorenzi** [comment]
why not simply  use $a7dd register?

**Comment by Samuel-DEVULDER** [comment]
I'm usure this register is available for the MO5, but on the pc128 op why not.

**Comment by Samuel-DEVULDER** [comment]
I have found the way to change the border color on the mo5 in http://dcmoto.free.fr/documentation/moniteur-mo5-putch/moniteur-mo5-putch_src.txt (label "TOUR"), assuming B holds the border color, this
```
PRA     EQU     $A7C0
        LSLB
        ANDB    #%00011110  
        STB     ,-S
        LDA     PRA             
        ANDA    #%11100001      
        ADDA    ,S+
        STA     PRA          
```
Changes the border very quickly :)

**Comment by Samuel-DEVULDER** [comment]
from the (history )[https://github.com/spotlessmind1975/ugbasic/commits/main/ugbc/src/targets/pc128op/color_border.c] it look like this issue has been fixed in the code.

Shall I close the issue ?

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER **I agree.**
