### ISSUE TITLE
Little/bing endian issue

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#187]
https://github.com/spotlessmind1975/ugbasic/blob/8755290bcfa4c977c18aa14fc91d2c5bbfca4ea4/ugbc/src/targets/mo5/_cleanup.c#L256

Here we have "int rest;" and we do fwrite(&rest, 1, 1, ...), this mean that on BigEndian manchine we write to MSB which is 0. I think rest should be declared as "unsigned char rest;"

**Comment by spotlessmind1975** [comment]
See #188
