### ISSUE TITLE
Buggy conversion to K7 for certain file sizes.

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#188]
First a small issue:

https://github.com/spotlessmind1975/ugbasic/blob/8755290bcfa4c977c18aa14fc91d2c5bbfca4ea4/ugbc/src/targets/mo5/_cleanup.c#L256

Here we have "int rest;" and we do fwrite(&rest, 1, 1, ...), this mean that on BigEndian manchine we write the MSB which is 0. I think rest should be declared as "unsigned char rest;"

The the bigger one: I have the following basic source:
```
BITMAP ENABLE
COLOR BORDER BLACK
CLS BLACK
DO
   x=RND(SCREEN WIDTH)
   y=RND(SCREEN HEIGHT)
   c=RND(SCREEN COLORS)
   PRINT x,y,c
   PLOT x,y,c
LOOP
```
which generate a 11930 bytes binary file. 

When generating the K7 we get to line https://github.com/spotlessmind1975/ugbasic/blob/8755290bcfa4c977c18aa14fc91d2c5bbfca4ea4/ugbc/src/targets/mo5/_cleanup.c#256 with cnt=251. This mean that 251 bytes of the final block was written so far. 

But see then what happen when we write the final part of the file:
```
		crc((unsigned char *)&preend,3,&sum);
		fwrite(&preend,3,1,fw); // cnt = 254 (here we should then write the checksum)
		crc((unsigned char *)&runaddr,2,&sum);
		fwrite(&runaddr,2,1,fw); // cnt = 256
		chk=cmpl(sum);
		sum=0;
		fwrite(&chk,1,1,fw); // cnt=257
```
So the final block is 257 bytes long (checksum included). This is invalid, and as a result, the K7 file can't be loaded:
![image](https://user-images.githubusercontent.com/33961444/139694125-7db5ff89-a3d0-434c-91ba-f83a25c804ce.png)

I think the conversion is buggy for certain file sizes.

**Comment by spotlessmind1975** [comment]
Fixed and added example to check that the executable is built correctly:
https://github.com/spotlessmind1975/ugbasic/blob/main/examples/graphics_plot_05.bas

**Comment by Samuel-DEVULDER** [comment]
> Fixed and added example to check that the executable is built correctly: https://github.com/spotlessmind1975/ugbasic/blob/main/examples/graphics_plot_05.bas

So you fixed it. Good :)

On my side I was using the following version which is simpler for me to understand (less magick values, less conditionals, and overall less computation). 
```
/* http://dcmoto.free.fr/documentation/moniteur-mo5-casst/moniteur-mo5-casst_src.txt */
static unsigned char blk[257];
static void new_blk(int type) 
{
    blk[0] = type;                  /* set type ok k7 block: 0=file-name, 1=file-data, 0xFF=end-of-file */
    blk[1] = 0;                     /* len = 0 */
    blk[256] = 0;                   /* checksum = 0 */
}
static void out_blk(FILE *f) 
{
    static unsigned char hdr[]={1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0x3c,0x5a}; /* k7 block-header */
    int pos = 2 + blk[1];		    /* get checksum pos */
	blk[1] = pos;					/* update block len */
    blk[pos] = 256 - blk[256];      /* complement checksum */
    fwrite(hdr, sizeof(hdr), 1, f); /* write block header */
    fwrite(blk, pos+1, 1, f);       /* then block content */
    new_blk(blk[0]);                /* prepare a new block of the same kind */
}

static void write_byte(FILE *f, int byte) 
{
    blk[256] += (unsigned char)byte;/* update checksum */
    blk[2 + blk[1]++] = byte;       /* update index & store byte */
    if(254 == blk[1]) out_blk(f);   /* when block is full, write it */
}
static void write_word(FILE *f, int word) 
{
    write_byte(f, word >> 8);
    write_byte(f, word & 255);
}
static void write_bytes(FILE *f, void *array, int len) 
{
    unsigned char *ptr = array;
    size_t cnt = len;
    while(cnt--) write_byte(f, *ptr++);
}

int convertbintok7(Environment * _environment)
{
    unsigned short start=0x3000;
    unsigned short size;
    unsigned short runaddr=0x3000;
    FILE *fr,*fw;
    char nome[12];
    char source[20];
    char destin[100];

    // Rename the output file into a temporary filename
    char temporaryFileName[MAX_TEMPORARY_STORAGE];
    sprintf(temporaryFileName, "%s.bin", tmpnam(NULL) );
    rename( _environment->exeFileName, temporaryFileName );
    
    fr=fopen(temporaryFileName,"rb");
    if(!fr) 
    {   
        CRITICAL_CANNOT_OPEN_EXECUTABLE_FILE( temporaryFileName );
    }

    if(frmt(_environment, "main.exe",strlen("main.exe"),nome))
    {
        CRITICAL("abort");
    }

    unsigned char file_type[]={0x02,0x00,0x00}; /* binary k7 file */

    fr=fopen(temporaryFileName,"rb");

    strcpy(destin,_environment->exeFileName);
    fw=fopen(destin,"wb");

    fseek(fr, 0L, SEEK_END);
    size = ftell(fr);
    rewind(fr);

    new_blk(0); /* k7 block 0: file name + type */
    write_bytes(fw, &nome[0], sizeof(nome)-1); /* file name */
    write_bytes(fw, &file_type[0], 3); /* file type */
    out_blk(fw); /* done with block 0 */
    
    new_blk(1); /* k7 block 1: content of file */
    write_byte(fw, 0); /* binary chunk */
    write_word(fw, size); /* size of chunk */
    write_word(fw, start); /* load address */
    for (int i=0;i<size;i++)
    {
        unsigned char byt;
        fread(&byt,1,1,fr);
        write_byte(fw, byt); /* data */
    }
    
    write_byte(fw, 0xff); /* execution chunk */
    write_word(fw, 0x0000); /* len = 0 */
    write_word(fw, runaddr); /* exec address */
    out_blk(fw); /* done with k7 block 1 */
    
    new_blk(0xff); /* k7 block 0xff : end of k7 file */
    out_blk(fw); /* done with it */
        
    fclose(fr);
    fclose(fw);
    
    return 0;
}
```
The idea behind this version is to have an API do deal with [low-level K7 blocks](http://dcmoto.free.fr/documentation/moniteur-mo5-casst/moniteur-mo5-casst_src.txt):
* 1 byte for type of k7-block (0=filename, 1=data, 0xff=end of file)
* 1 byte=2+ len(data)
* data (up to 254 bytes)
* 1 byte for checksum
and on top of this write the thomson binary file structure : 0x00 <data-len: 2 bytes> <load-addr:2 bytes> ..data.. 0xff 0x0000 <exec-addr:2 bytes>) and let the low-level place the checksum where it needs to be.

Feel free to use this as you want (minimal test were done, but it works so far.)

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER  How about a pull request?

**Comment by Samuel-DEVULDER** [comment]
Actually I'm quite new to collaborating via github (my project are "me-only"), and I've never done any pull-request. May be it is time to start...

What should I do ? Fork your project on my own git, checkout this one, commit my changes on my own version, and when I find some nice piece of code to share with your github I do a pull-request. Is that the normal way to proceed (in a nutshell) ?

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER Don't worry, I'm new too. ;-)

I [find out this guide](https://jarv.is/notes/how-to-pull-request-fork-github/) by googling around:

1. fork the repository 
2. clone your new fork locally
3. track the original repository as a remote of the fork
4. create a new branch 
5. apply your changes
6. add, commit, and push the changes
7. submit your pull request

The main difference seems that you have to commit your changes on a separate branch (a topical branch?) of your repository -- in this way, the change is isolated from my forward commits. For the point 7 you have to head over to the original repository's "Pull Requests" tab, and you should see an automatic suggestion from GitHub to create a pull request from your new branch.

Ok, I hope this help. ^_^

**Comment by Samuel-DEVULDER** [comment]
> @Samuel-DEVULDER How about a pull request?

Hmm I tried this: https://github.com/spotlessmind1975/ugbasic/pull/207

Is this correct ?

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER  **I would say it's a great job!**

I reply directly to the pull request.

**Comment by spotlessmind1975** [comment]
Fixed
