### ISSUE TITLE
Spurious random numbers

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#192]
If you consider the following basic program:
```
BITMAP ENABLE
COLOR BORDER BLACK
CLS BLACK
DO
   x=RND(SCREEN WIDTH)
   y=RND(SCREEN HEIGHT)
   c=RND(SCREEN COLORS)
   PEN 1
   PRINT x,y,c
   PLOT x,y,c
LOOP
```
You will see that very quickly the printed numbers go to this (seemingly) repeating pattern ("c" being 0 at every iteration, resulting in the absence of colorful stars)
![dcmoto02](https://user-images.githubusercontent.com/33961444/140191678-6d4bf7f9-5746-4409-afc8-bba6b4ce9427.png)

This indicates that the random number generator isn't really random (tested with target=MO5).

**Comment by spotlessmind1975** [comment]
Fixed (removed PRINT from example, since it mess the graphical output).
