### ISSUE TITLE
Vestigial code on cpu6809_move_8bit_with_offset

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#214]
I'm not sure this is a bug, but while revisiting 6809.c with optimized ASM, I discovered that these two different piece of code look suspiciously the same. Is there any reason for this ?

https://github.com/spotlessmind1975/ugbasic/blob/e11182d3958f245f493ef11692e02816786d6f2d/ugbc/src/hw/6809.c#L3755-L3768

https://github.com/spotlessmind1975/ugbasic/blob/e11182d3958f245f493ef11692e02816786d6f2d/ugbc/src/hw/6809.c#L3772-L3785

**Comment by spotlessmind1975** [comment]
I did a brief research on the use of the two routines.

The first (`cpu6809_move_8bit_with_offset`) is used massively to copy (move) a value from a variable (`_source`) to a memory area whose address is stored in a variable (`_value`), to which an explicit and direct offset is added ( `_offset`). It is used primaly to update programmatically the content of dynamic strings.

The second (`cpu6809_move_8bit_indirect_with_offset`) is not used at all.

At this point I assume that it is of the vestigial code, which survived a massive refactoring which has not been completed. In fact the correct name for the function should be `cpu6809_move_8bit_indirect_with_offset` and the implementation is the current one of `cpu6809_move_8bit_with_offset`.

I'll fix it in the next release.

**Comment by spotlessmind1975** [comment]
Code refactorized, and removed vestigial code.

**Comment by Samuel-DEVULDER** [comment]
These two:
https://github.com/spotlessmind1975/ugbasic/blob/36774ecc6831c8324c18f9692af2382a354c7c5a/ugbc/src/hw/6809.c#L3858-L3889
https://github.com/spotlessmind1975/ugbasic/blob/36774ecc6831c8324c18f9692af2382a354c7c5a/ugbc/src/hw/6809.c#L3891-L3922

Also look the same. Reopen ?

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER **thanks for the observation!**

In this case it is not a vestigial code. Let's say it's a version of the routine which, instead of storing a direct value, retrieves it from a memory location. Perhaps the name of the function is unfortunate, but if you see its use, you understand that it is complementary to others that work with constant values instead.
