### ISSUE TITLE
mask not shifted correctly for 32bit const

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#216]
https://github.com/spotlessmind1975/ugbasic/blob/e11182d3958f245f493ef11692e02816786d6f2d/ugbc/src/hw/6809.c#L2613

Here, for the most significant word, the mask is right shifted by 8 bits (_mask>>8), but I think it should be shifted by 245 to get its most significant byte.

**Comment by spotlessmind1975** [comment]
Fixed.
