### ISSUE TITLE
[6809] Access to $0020 in place of $2020

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#220]
https://github.com/spotlessmind1975/ugbasic/blob/a9c209956e4df7d1cf1d7dec512309538f3460d6/ugbc/src/hw/6809/sqr.asm#L48

The current implementation of sqrt() uses extended (==16 bits, eg `$something`) addressing mode, in place of the direct-page mode (==8 bits, eg. `<$something`), this results in screen garbage since [$0020 is right in the VRAM](https://www.cjoint.com/doc/21_11/KKpajqDUy5x_memmap.html#4987) of the MO5/PC128po machines.
![dcmoto01](https://user-images.githubusercontent.com/33961444/141704438-b7e7a620-e89e-4957-9c27-553f47f149e0.png)

Note: this might also be present for other routines since I already saw such video artifact with other programs in the examples/ folder.

**Comment by spotlessmind1975** [comment]
I should have corrected it, using the `<` syntax to indicate that the register should refer to the `DP` register (equal to `$20` on Olivetti Prodest PC128 and Thomson MO5, while it will be `$00` on Dragon computers). However, you should check if the problem has actually been solved, or if you need to do a deeper review of the assembly code.

**Comment by Samuel-DEVULDER** [comment]
Problem seem solved, but I have spotted another place where we refer to extended address where direct-page was intended, see:

https://github.com/spotlessmind1975/ugbasic/blob/07033897c122479615bda928e3143f072d6da710/ugbc/src/hw/ef936x/text_at.asm#L79

https://github.com/spotlessmind1975/ugbasic/blob/07033897c122479615bda928e3143f072d6da710/ugbc/src/hw/pc128op/vars.asm#L79

There surely are others around this in text routines.

**Comment by Samuel-DEVULDER** [comment]
Another strange thing.. https://github.com/spotlessmind1975/ugbasic/blob/07033897c122479615bda928e3143f072d6da710/ugbc/src/hw/ef936x/text_at.asm#L404-L424

We access MATHPTR5 both via direct-page and via extended

**Comment by Samuel-DEVULDER** [comment]
Another strange thing.. https://github.com/spotlessmind1975/ugbasic/blob/07033897c122479615bda928e3143f072d6da710/ugbc/src/hw/ef936x/text_at.asm#L404-L424

We access MATHPTR5 both via direct-page and via extended.

**Comment by spotlessmind1975** [comment]
Another fix. :)
