### ISSUE TITLE
Refer to extended address where direct-page was intended

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#223]
Problem seem solved, but I have spotted another place where we refer to extended address where direct-page was intended, see:

https://github.com/spotlessmind1975/ugbasic/blob/07033897c122479615bda928e3143f072d6da710/ugbc/src/hw/ef936x/text_at.asm#L79

https://github.com/spotlessmind1975/ugbasic/blob/07033897c122479615bda928e3143f072d6da710/ugbc/src/hw/pc128op/vars.asm#L79

There surely are others around this in text routines.

_Originally posted by @Samuel-DEVULDER in https://github.com/spotlessmind1975/ugbasic/issues/220#issuecomment-969331883_

**Comment by spotlessmind1975** [comment]
Fixed but it needs to check other assembly source code.
