### ISSUE TITLE
_frame_width undeclared

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#224]
https://github.com/spotlessmind1975/ugbasic/blob/608c3d006822f92995a0bc68ec81c3765422bd95/ugbc/src/hw/ef936x.c#L674

Should this be "_width" instead ? (same for _frame_height)

**Comment by spotlessmind1975** [comment]
Please forgive me but I'm doing some heavy code refactoring, which is to introduce a necessary function which is the GET IMAGE. If you can try to go back to commit before starting this operation (commit a59e9ecbb92ba6088199e53f72da46ecdfaa5d92 ). Thanks and sorry again for the inconvenience!

**Comment by spotlessmind1975** [comment]
Fixed.

**Comment by Samuel-DEVULDER** [comment]
Yeah no problem. Maybe I'm just reporting things too early :) Actually I was trying to understand why examples/arrays_example_01.bas doesn't display any of price$(0) or price$(1) on the MO5. Instead I can observe some strange patterns in the top of string. This is likely to be the (in)famous extended vs direct-page access somewhere
![dcmoto02](https://user-images.githubusercontent.com/33961444/141941570-365bff65-23a1-4ab5-8d71-57a7b0d40796.png)
:
