### ISSUE TITLE
[MO5] WHITE is RED

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#226]
https://github.com/spotlessmind1975/ugbasic/blob/3ce9b5abf3ea97ecc2c97a90db633dd1d0873a84/examples/graphics_plot_02.bas#L25

Is there a specific reason why, on the MO5, the pixel colors are RED when the code says WHITE ?
DefaultThomson (TO/MO) colors from 0 to 7 are: 0=BLACK, 1=RED, 2=GREEN, 3=YELLOW, 4=BLUE, 5=VIOLET, 6=CYAN, 7=WHITE, and for 8 to 15 it is a bit more difficult to give a name but the [wiki](https://fr.wikipedia.org/wiki/Mode_graphique_des_Thomson_MOTO) says: 8=GRAY, 9=OLD_ROSE, 10=LIGHT_GREEN, 11=SAND, 12=SKY_BLUE, 13=LIGHT_MAGENTA, 14=LIGTH_CYAN, 15=ORANGE.

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER **thank you for bug reporting!**

One question: but can the MO5 redefine the palette like the MO6, using the `$A7DA` register? If that can't happen, then this is the reason. If it cannot redefine the palette, then it will be necessary to split the code between the MO6 chipset and the MO5 chipset, which are obviously different EF936x chipsets.

Let me know.

**Comment by Samuel-DEVULDER** [comment]
The MO5 (nor the TO7(/70) if you want one day to support the full thomson family) can redefine the palette.

So I suppose the definition 
https://github.com/spotlessmind1975/ugbasic/blob/d7f996680c17e50f8fec0a623c1646c692679d05/ugbc/src/hw/ef936x.c#L40
should be #ifdef __pc128op__ only, and another one defined for __mo5__.

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER **you was quite right!**

That change wouldn't have been enough, because it deals with image analysis for transformation into native bitmaps and colormaps. Actually it was necessary to redefine the color constants.

Anyway... bug fixed!
