### ISSUE TITLE
Add support for DIV instruction

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#228]
I'm thinkind about something like an instruction like `DIV p,q,r` which will be equivalent to
```
r = p MOD q
p = p / q
```
but in a faster way since the asm already does the MOD operation during the division.

Note: maybe the final argument (",r") should be made optional if one only needs a fast modification of p, for instance when doing things like `DIV array(k),divisor` as the address of array(k) would only be evaluated once.

**Comment by spotlessmind1975** [comment]
Implemented. Note that the operation **does not change** the type of the incoming variable. Also, if the remainder parameter is used, and the relative variable does not exist, it will be created according to the default variable type. It follows that, to be safe, it is best to create the variable for the rest.

**Comment by Samuel-DEVULDER** [comment]
I have a specific case to use this feature: high precision arithmetic.
```
REM divides TAB() by div
DIVIDE:
	r = 0
	FOR i=0 TO TABSZ
                ADD TAB(i),BASE*r
                DIV TAB(i),div,r
	NEXT
RETURN

REM multiply TAB() by mul
MULTIPLY:
	r = 0
	FOR i=TABSZ TO 0 STEP -1
		ADD r,TAB(i)*mul
		DIV r,BASE,TAB(i)
	NEXT
RETURN
```
_(go figure out what it can compute :) )_

**Comment by Samuel-DEVULDER** [comment]
I have a specific case to use this feature: high precision arithmetic.
```
REM divides TAB() by div
DIVIDE:
	r = 0
	FOR i=0 TO TABSZ
                t = TAB(i) + BASE*r
                DIV t,div,r
                TAB(i) = t
	NEXT
RETURN

REM multiply TAB() by mul
MULTIPLY:
	r = 0 
	FOR i=TABSZ TO 0 STEP -1
		ADD r,TAB(i)*mul
		DIV r,BASE,TAB(i) : REM or DIV r,BASE,t : TAB(i) = t if TAB(i) isn't accepted as argument
	NEXT
RETURN
```
_(go figure out what it can compute :) )_
