### ISSUE TITLE
Add support for DEFINE DEFAULT TYPE

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#229]
In the current version of ugBASIC, by definition the variables have a 16-bit value (WORD). Instead, it would be appropriate to implement a statement with which the types of variables can be defined by default. 

Example:

     y = 84 : ' y = WORD

     DEFINE DEFAULT TYPE BYTE

     x = 42 : ' x = BYTE

A first preliminary implementation is available at commit 8e6ebab .

**Comment by Samuel-DEVULDER** [comment]
Oh I thought the type was given via the "x = (8BIT)value" construct. I'm I totally mislead ?

Some basic use DEFINT/DEFLNG & friends to predefine the type according to the first letter of the variable. Hence with DEFINT A-B:DEFLNG C-D, Avar and Bar variables are automatically 16bits while Cfoo and Dbar are automatically 32bits.  They usually also allow specification of type via an identifier suffix: Dbar% is a 16 bit variable (different from Dbar), and Avar& a 32bit one (different from Avar).

**Comment by spotlessmind1975** [comment]
> Oh I thought the type was given via the "x = (8BIT)value" construct. I'm I totally mislead ?

@Samuel-DEVULDER the problem is not with the explicit definition (by casting, in you case) but with the implicit definition. If I write

       x = value

then ugBASIC will generate a variable of the WORD type for `x`, which occupies 2 bytes. Often, unnecessarily. At the same time, it is tedious to specify the type for each variable or function parameter, and currently suffix is supported only for strings (`$`). Take here an example:


      VAR x AS BYTE = value
      x = (BYTE) value
      PROCEDURE p [ x AS BYTE ]

At the beginning I also thought about the standard syntax of the most advanced BASICs, like the one you kindly suggested to me. I do not rule out that, one day, it will be supported. Actually my aim is to reduce the footprint of a program I am writing, and I have found that I can save a lot of space by switching from standard 2-byte variables to 1-byte variables.

Unfortunately the first "naive" implementation does not work well (the quoted commit), and therefore more effort is required.

That's why I wrote down the task.

**Comment by Samuel-DEVULDER** [comment]
Oh yes, and I sometimes see strange things about this implicit size-guess. Consider this:
```
CONST a=1000
b=2*a+1
c=a+a+1
```
And look at the ASM, you'll find (MO5, but probably the same on every plateform):
```
_b rzb 4
_c rzb 2
```
b is 32 bits, while c is only 16!

Doing `b=(16BIT)2*a+1` doesn't seem to help.

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER it seems to me that it works correctly, but maybe I'm the one who has a strange conception of induced types.  I'll start with your example and, step by step, indicate how I would interpret it if I were ugBASIC (or, at least, I hope so!). 

    ' by default, constants are WORDs
    CONST a=1000
    ' WORD (2) * WORD (a) -> DWORD (2*a) + WORD(1) -> DWORD (2*a+1) -> DWORD (b)
    b=2*a+1 : 
    ' WORD(a) + WORD(a) + WORD(1) -> WORD( a+a+1) -> WORD(c)
    c=a+a+1

> Doing b=(16BIT)2*a+1 doesn't seem to help to reduce b down to 16 bits.

That is really strange. Have you tried with this?

      b = (16 BIT) (2*a+1)

**Comment by Samuel-DEVULDER** [comment]
Oh I see: multiplication of 16 bits gives a 32 bit result.

> ' by default, constants are WORDs
> CONST a=1000
> ' WORD (2) * WORD (a) -> DWORD (2*a) + WORD(1) -> DWORD (2*a+1) -> DWORD (b)
> b=2*a+1 : 
> ' WORD(a) + WORD(a) + WORD(1) -> WORD( a+a+1) -> WORD(c)
> c=a+a+1

So the 2*a version is not only slower because of the multiplication, but also because all of the remaining calculation is done in 32bits.

I presume there is no such a thing as a 16x16->16 multiplicatio.

> That is really strange. Have you tried with this?
> 
> ```
>   b = (16BIT) (2*a+1)
> ```

That works !

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER **great, and I think you are right.**

Unfortunately I fear it is inevitable: it is a mathematical question, not a computer one. It is possible that operands occupy more than 8 bit on average, and therefore their product (that can be seen as a generic "sum of bits") will occupy more than 16 bit, causing a representation error if the result is not promoted to 32 bit.

> I presume there is no such a thing as a 16x16->16 multiplication.

It is present an 8x8->16 bit multiplication (when you are using 8 bit operands) and, only with the current branch, we also have an optimized version of multiplication (`**`) which works with constants that are powers of 2. So:

     a = (BYTE)42
     b = (BYTE) 2
     c = a * b : ' c is a WORD (16 bit)
     d = a ** #2 : ' c is left shifted by 1 and d remains a BYTE

Note the `#...` notation for number 2. It is needed to tell ugBASIC that you want to consider the 2 as a real constant. Otherwise, it will create a temporary variable, that is suitable for following calculations.

I hope this helps. :)

**Comment by spotlessmind1975** [comment]
Implemented.
