### ISSUE TITLE
Add support for MUL instruction

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#230]
Extra thinking: ... and related to these "fast modification" operations, `MUL x,y` (x=x*y) or `DIV x,y` (x=x/y) would be interesting (especially when the address of x is costly to evaluate, eg: array access).

_Originally posted by @Samuel-DEVULDER in https://github.com/spotlessmind1975/ugbasic/issues/227#issuecomment-972691879_

**Comment by spotlessmind1975** [comment]
Implemented. Note that the implementation **does not promote** the target type. 

So if you do something like:

     a = (WORD) 42: b = (BYTE) 2
     MUL a, b

the result will (`a`) remain of type WORD. 

So it is possible that there may be "overflows".

**Comment by Samuel-DEVULDER** [comment]
Oh great! Does it accept array(index) as first argument as well ?

**Comment by spotlessmind1975** [comment]
> Oh great! Does it accept array(index) as first argument as well ?

Thanks! Not currently, but it will covered by #227 for sure. ;)
