### ISSUE TITLE
[MO5] RIGHT$() works strangely

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#231]
Consider this code:
```
PRINT RIGHT$("123456",1)
PRINT RIGHT$("123456",2)
PRINT RIGHT$("123456",3)
PRINT RIGHT$("123456",4)
PRINT RIGHT$("123456",5)
PRINT RIGHT$("123456",6)
HALT
```
On the MO5 it prints:
![Sans titre](https://user-images.githubusercontent.com/33961444/142496576-9115328c-ab65-427c-becd-0ec95adf2433.png)

Which doesn't look correct to me (or I dont spot the logic behind it.)

**Comment by Samuel-DEVULDER** [comment]
Pk I think I have spotted the cause for this. 
```
diff --git a/ugbc/src/targets/common/_infrastructure.c b/ugbc/src/targets/common/_infrastructure.c
index 4282ea3..37529cc 100755
--- a/ugbc/src/targets/common/_infrastructure.c
+++ b/ugbc/src/targets/common/_infrastructure.c
@@ -2772,11 +2772,11 @@ Variable * variable_string_right( Environment * _environment, char * _string, ch
             cpu_move_8bit( _environment, size->realName, size2->realName );
             cpu_math_sub_8bit( _environment, size2->realName, position->realName, size2->realName );
             cpu_dsfree( _environment, result->realName );
-            cpu_dsalloc( _environment, size2->realName, result->realName );
+            cpu_dsalloc( _environment, position->realName, result->realName );
             cpu_dsdescriptor( _environment, result->realName, address2->realName, size2->realName );
             cpu_math_add_16bit_with_8bit( _environment, address->realName, size->realName, address->realName );
             cpu_math_sub_16bit_with_8bit( _environment, address->realName, position->realName, address->realName );
-            cpu_mem_move( _environment, address->realName, address2->realName, size2->realName );
+            cpu_mem_move( _environment, address->realName, address2->realName, position->realName );
             break;
         }

```

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER **I arrived only slightly late!**

I solved the problem roughly a different approach, just by omitting a step, and both for static and dynamic strings. Below I put the diff. In any case, I don't understand how it was possible: the tests I conducted had given positive results, and I don't seem to have touched this part. I can't really explain what happened.

	git diff 33531ff dbe271d
	diff --git a/ugbc/src/targets/common/_infrastructure.c b/ugbc/src/targets/common/_infrastructure.c
	index 4282ea3..47d9ae8 100755
	--- a/ugbc/src/targets/common/_infrastructure.c
	+++ b/ugbc/src/targets/common/_infrastructure.c
	@@ -2769,8 +2769,7 @@ Variable * variable_string_right( Environment * _environment, char * _string, ch
	             cpu_move_8bit( _environment, string->realName, size->realName );
	             cpu_addressof_16bit( _environment, string->realName, address->realName );
	             cpu_inc_16bit( _environment, address->realName );
	-            cpu_move_8bit( _environment, size->realName, size2->realName );
	-            cpu_math_sub_8bit( _environment, size2->realName, position->realName, size2->realName );
	+            cpu_move_8bit( _environment, position->realName, size2->realName );
	             cpu_dsfree( _environment, result->realName );
	             cpu_dsalloc( _environment, size2->realName, result->realName );
	             cpu_dsdescriptor( _environment, result->realName, address2->realName, size2->realName );
	@@ -2779,14 +2778,13 @@ Variable * variable_string_right( Environment * _environment, char * _string, ch
	             cpu_mem_move( _environment, address->realName, address2->realName, size2->realName );
	             break;
	         }
	-        case VT_DSTRING: {
	+        case VT_DSTRING: {
	             Variable * address = variable_temporary( _environment, VT_ADDRESS, "(result of right)" );
	             Variable * size = variable_temporary( _environment, VT_BYTE, "(result of right)" );
	             Variable * address2 = variable_temporary( _environment, VT_ADDRESS, "(result of right)" );
	             Variable * size2 = variable_temporary( _environment, VT_BYTE, "(result of right)" );
	             cpu_dsdescriptor( _environment, string->realName, address->realName, size->realName );
	             cpu_move_8bit( _environment, size->realName, size2->realName );
	-            cpu_math_sub_8bit( _environment, size2->realName, position->realName, size2->realName );
	             cpu_dsfree( _environment, result->realName );
	             cpu_dsalloc( _environment, size2->realName, result->realName );
	             cpu_dsdescriptor( _environment, result->realName, address2->realName, size2->realName );
	`

**Comment by spotlessmind1975** [comment]
Sorry, this is the real diff:

	asimov@orville:/usr/src/ugbasic$ git diff  33531ff 91451fa ugbc/src/targets/common/_infrastructure.c
	diff --git a/ugbc/src/targets/common/_infrastructure.c b/ugbc/src/targets/common/_infrastructure.c
	index 4282ea3..0051b2e 100755
	--- a/ugbc/src/targets/common/_infrastructure.c
	+++ b/ugbc/src/targets/common/_infrastructure.c
	@@ -2769,8 +2769,7 @@ Variable * variable_string_right( Environment * _environment, char * _string, ch
	             cpu_move_8bit( _environment, string->realName, size->realName );
	             cpu_addressof_16bit( _environment, string->realName, address->realName );
	             cpu_inc_16bit( _environment, address->realName );
	-            cpu_move_8bit( _environment, size->realName, size2->realName );
	-            cpu_math_sub_8bit( _environment, size2->realName, position->realName, size2->realName );
	+            cpu_move_8bit( _environment, position->realName, size2->realName );
	             cpu_dsfree( _environment, result->realName );
	             cpu_dsalloc( _environment, size2->realName, result->realName );
	             cpu_dsdescriptor( _environment, result->realName, address2->realName, size2->realName );
	@@ -2779,14 +2778,13 @@ Variable * variable_string_right( Environment * _environment, char * _string, ch
	             cpu_mem_move( _environment, address->realName, address2->realName, size2->realName );
	             break;
	         }
	-        case VT_DSTRING: {
	+        case VT_DSTRING: {
	             Variable * address = variable_temporary( _environment, VT_ADDRESS, "(result of right)" );
	             Variable * size = variable_temporary( _environment, VT_BYTE, "(result of right)" );
	             Variable * address2 = variable_temporary( _environment, VT_ADDRESS, "(result of right)" );
	             Variable * size2 = variable_temporary( _environment, VT_BYTE, "(result of right)" );
	             cpu_dsdescriptor( _environment, string->realName, address->realName, size->realName );
	-            cpu_move_8bit( _environment, size->realName, size2->realName );
	-            cpu_math_sub_8bit( _environment, size2->realName, position->realName, size2->realName );
	+            cpu_move_8bit( _environment, position->realName, size2->realName );
	             cpu_dsfree( _environment, result->realName );
	             cpu_dsalloc( _environment, size2->realName, result->realName );
	             cpu_dsdescriptor( _environment, result->realName, address2->realName, size2->realName );

**Comment by Samuel-DEVULDER** [comment]
Code-footprint is also reduced. I presume this is good as well :)
