### ISSUE TITLE
PLOT ERASE ?

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#232]
This bit of asm
https://github.com/spotlessmind1975/ugbasic/blob/91451fa9a6409455d3c2a1269f49c91eae51fc64/ugbc/src/hw/ef936x/plot.asm#L200
seem to indicated there is a possibility for PLOT to erase a pixel , but I do not find how to do this in ugbasic.

This feature would be very helpful to prevent artifact on the thomson machines with this code I'm working out
```
REM Starfield, by S.Devulder for ugBasic

CONST numr  = 1000 : REM num of random position in pool 
CONST nums  =   50 : REM number of stars in starfield
CONST speed =    8 : REM speed of stars (smaller = faster)

DIM xrnd AS POSITION (numr+1)
DIM yrnd AS POSITION (numr+1)

DIM xtab AS POSITION (nums+1)
DIM ytab AS POSITION (nums+1)
DIM ctab AS BYTE (nums+1)

BITMAP ENABLE
COLOR BORDER BLACK
CLS BLACK

REM init pool of random positions (faster than calling RND over and over again)
FOR i=0 TO numr
	xrnd(i) = RND(SCREEN WIDTH)
	yrnd(i) = RND(SCREEN HEIGHT)
NEXT
irnd = 0

REM initial stars
FOR i=0 TO nums
	ctab(i) = RND(SCREEN COLORS - 1) + 1
	xtab(i) = RND(SCREEN WIDTH)
	ytab(i) = RND(SCREEN HEIGHT)	
	PLOT xtab(i),ytab(i),ctab(i)
NEXT

x0 = (SCREEN WIDTH / 2)
y0 = (SCREEN HEIGHT / 2)

DO
	PLOT x0,y0,WHITE
	FOR i=0 TO nums
		x = xtab(i)
		y = ytab(i)
		
		z = x
		t = y
		
		ADD x, (x - x0)/speed
		ADD y, (y - y0)/speed
		
		IF (x OR y)<0 OR (y>=SCREEN HEIGHT) OR (x>=SCREEN WIDTH) THEN
			REPEAT
				x = xrnd(irnd)
				y = yrnd(irnd)
				ADD irnd,1,0 TO numr
			UNTIL ((x-x0)/speed) AND ((y-y0)/speed) : REM prevent stars too close to (x0,y0) as they don't move if both expression are 0
		ENDIF
		
		xtab(i) = x
		ytab(i) = y
		
		PLOT z,t,ERASE : REM Inexistant MODE ?
		PLOT x,y,ctab(i)
	NEXT
	joy = JOY(0)
	IF joy THEN
		dx = 0
		dy = 0
		IF joy HAS BIT UP    THEN : dy = -1 : ENDIF
		IF joy HAS BIT DOWN  THEN : dy =  1 : ENDIF
		IF joy HAS BIT LEFT  THEN : dx = -1 : ENDIF
		IF joy HAS BIT RIGHT THEN : dx =  1 : ENDIF
		PLOT x0,y0,ERASE : REM Inexistant MODE ?
		ADD x0,dx,0 TO SCREEN WIDTH-1
		ADD y0,dy,0 TO SCREEN HEIGHT-1
	ENDIF
LOOP
```

At the moment this code seem to work because ERASE = 0 = BLACK, but this is not what I wanted as it plots a black pixel instead of erasing it (eg AND-out or XOR the bit in video memory). This leave some artefacts on screen. 

One can see them very easily with this small snippet:
```
BITMAP ENABLE
COLOR BORDER BLACK
CLS BLACK

PLOT 0,100,7
FOR i=1 TO 319
	PLOT i-1,100,ERASE
	PLOT i,100,7
	WAIT 20MS
NEXT
HALT
```
A single point is supposed to go from left to right, but instead we've got a kind of horizontal segment increasing every 8 pixels. 
_(Yeah it isn't a bug, but a worm :) )_

**Comment by Samuel-DEVULDER** [comment]
I have an idea which require no change except for the MO5 or may be other platforms with color clashes.

The idea is: when we want to plot a color that matches the background (paper) color for the current group of pixel (8x1 for Thomson, and possibly 8x§8 for ZX-spectrum), instead of setting the bit and changing the foreground(ink) color to the one provided, one can simply clear that bit in video. It'll inherit the background color which is the color we asked without affecting any other pixel nearby (because we don't change the ink color).

This would go along with an optimisez PLOT that I might propose as PR for the MO5  as soon I test my implementation it working correctly. What do you think about that ?

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER **sounds like a great idea to me!**

Now I carefully examine both your source (which I would add to the examples, if you do not mind) and your implementation proposal. I think it is an interesting approach to eliminate artifacts, which exist in all systems (especially Commodore, that suffers of this problem a bit).

**Comment by Samuel-DEVULDER** [comment]
Yeah, starfields are cool. Especially portable ones :)

It also permit to see the relative speed of the various implementations and tune "peephole optimizer" quite a bit (the one on my branch "6809opt" seem to do a wonderful job), and even make the compiler smarter. For instance speed is a power by two constant. So (x-x0)/speed can automatically be implemented in term of (possibly inlined) right shifts.

You can use it, but I haven't tested the "joy(0)" part as it seem not working on the Thomson&friend (possibly the ASM behind JOY is just empty at this point, I haven't checked yet :) .

**Comment by spotlessmind1975** [comment]
> Yeah, starfields are cool. Especially portable ones :)

 **You are right from all points of view!**

> the one on my branch "6809opt" seem to do a wonderful job

I can't wait to try it out ... soon I would like to come out with version 1.6, which has a lot of fixes (many on your input). I'd love to be able to put it in that output, but I don't want to rush you.

> (Note: I haven't found the way to use the "**" operator you used the other day)

Unfortunately it was a communication defect on my part. You should pull the last branch, where I should have fixed a trivial problem: the `**` operator was implemented in an "infix" fashion instead of generating a temporary value, as it should have been - and this created some problems in use because it had side effects.

**Comment by spotlessmind1975** [comment]
Closed because obsolete.
