### ISSUE TITLE
In-place variable add ?

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#236]
https://github.com/spotlessmind1975/ugbasic/blob/69031acd34e7c403b350f9f071db13b491f1c249/ugbc/src/targets/common/end_for.c#L68-L70

From what I understand, the index variable of a for loop is incremented with the previous code. That code uses and return a tmp variable which is then copied back to the index. This increase the memory footprint, but also is a bit slow since we copy back that temporary variable to the index instead of doing cpu_add_XXX() with same source as dest.

I suggest to have some variable_add_inplace(environment, variable, delta) which does this.

This can also be used to implement a fast "ADD x,y" that doesn't use a tmp variable, reducing the memory footprint even more.

**Comment by spotlessmind1975** [comment]
Implemented and tested.
