### ISSUE TITLE
Collision with ROM page 0 registers

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#243]
https://github.com/spotlessmind1975/ugbasic/blob/7d3fb2c6956e98d9e0500c2088d174fa5fbbe4e0/ugbc/src/hw/pc128op/vars.asm#L58

As one can see MATHPTR5 (used for screen colors) is in direct-page $19. At the moment direct-page is set in startup to be the same as 
 the one used by the ROM ($20xx). Hence MATHPTR5 collides with the STATUS flag, resulting in various bug as cursor becoming visible again. 

I think overriding the $20xx is not a good idea and could lead to heavier bugs as soon as one of the important ROM flags are altered.

I'd suggest to either use another location.

**Comment by Samuel-DEVULDER** [comment]
> I'd suggest to either use another location.

$21xx could be an option, but why not use $30xxx, eg the start of the programs. More specifically where the program variables like CURRENTMODE/BITMAPADDRESS resides.

**Comment by spotlessmind1975** [comment]
> I'd suggest to either use another location.

@Samuel-DEVULDER **thanks for the great observation!**

I have a similar problem in many other platforms, where usually the zero page registers are used by native ROM. Moving the base (`DP`) could be an idea, but before doing so, is there a map of the free locations of page zero? Or those used exclusively by BASIC (that we do not use)? We could relocate `MATHPTR5` (and the other variables) to that position.

Let me know.

**Comment by Samuel-DEVULDER** [comment]
Description of the memory map can be found on Pulmkomandy's [site](http://pulko.mandy.pagesperso-orange.fr/shinra/mo5_memmap.shtml). It is full.

On my side [I tested](https://github.com/Samuel-DEVULDER/ugbasic/commit/0306270c14e69de9aa5655066cdf28ac5586c48f) the use of the basic page ($21xx) and it seem to work fine so far.

**Comment by spotlessmind1975** [comment]
> Description of the memory map can be found on Pulmkomandy's site. It is full.

I just read the map and I agree with you, there are some unused locations but they are very few. 

Let's use `DP = #$21`.

You think about in the next pull request?

Thank you!

**Comment by Samuel-DEVULDER** [comment]
May be I can pull (this full branch)[https://github.com/Samuel-DEVULDER/ugbasic/tree/misc_thomson_changes] as it also contains routines for joystick and border colors, or is not atomic enough ?
(BTW you can test the updated starfield executable with working joystick & border with this following [temporary link](https://www.cjoint.com/doc/21_11/KKxinPmTvGx_starfield.zip). It also contains asm for comparison)

**Comment by spotlessmind1975** [comment]
Branch #245 merged.
