### ISSUE TITLE
Improve variable_bit() ?

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#246]
When looking at the ASM of the starfield, I discovered that the bit checking code took a lot of instructions. I rewrote the [`cpu6809_bit_check_extended()`](https://github.com/Samuel-DEVULDER/ugbasic/commit/de3d6b241ea8e7ee01fcf156185c8e3b981b26f4), but still the ASM looked lengthy and difficult to understand. This is because of the following code which uses lots of label & jumps:
https://github.com/spotlessmind1975/ugbasic/blob/33ff7da9540337141c8a328836026a2366e36af1/ugbc/src/targets/common/_infrastructure.c#L4185-L4194

The thing is I don't understand the goal of line 4188-4194 as `result->realName` already contains $00/$FF after the call to `cpu_bit_check_extended()`.

Is there any reason for this logic glue, or can this be eliminated making the code faster in addition to reduce the code-footprint?

Note: If I remove these lines, the starfield still works and the ASM looks much better:
```
_label136e0
	LDB #$03
	STB _Ttmp7
	LDD #$0000
	STD _Ttmp67
	STD _Ttmp67+2
	LDA _joy
	STA _Ttmp67+3
; peephole: rule #1 (STr->LDr)
;	LDA _Ttmp67+3
	LDB _Ttmp7
	CMPB #8
	BLO _label138eval
	LDA _Ttmp67+2
	CMPB #16
	BLO _label138eval
	LDA _Ttmp67+1
	CMPB #24
	BLO _label138eval
	LDA _Ttmp67
_label138eval
	LDX #_bit_check_extended_tab
	LDB _Ttmp7
	ANDB #7
	ANDA B,X
	BEQ _label138end
	LDA #$ff
_label138end
```

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER , **thank you for your in-depth analysis!**

> Is there any reason for this logic glue, or can this be eliminated making the code faster in addition to reduce the code-footprint?

You are right, it can be removed. Probably the original implementation of bit check extended did not return true/false, hence the need for final verification. Today it is no longer necessary.

**Comment by spotlessmind1975** [comment]
Fixed.
