### ISSUE TITLE
Assign 0 to BYTE not working

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#254]
When I run this code
```
10 frames = (BYTE)1
20 PRINT frames
30 frames = 0
40 PRINT frames
50 HALT
```
It prints 1 twice instead of 1 and then 0.

Inspection of ASM for line 30 do not show any write-access to _frames:
```
_linenumber30
	CLR _Ttmp14
	CLR _Ttmp14+1
	CLR _Ttmp15
; peephole: rule #4 (CLR->ST*)
	LDA _frames 
	STA _Ttmp15+1
	LDD _Ttmp14
	STD _Ttmp15
	LDB _Ttmp3
	JSR DSFREE
_linenumber40
```
I suspected "rule #4" to cause this issue, but when I disable it, the asm look like this:
```
_linenumber30
	CLR _Ttmp14
	CLR _Ttmp14+1
	CLR _Ttmp15
	CLR _Ttmp15+1
	LDA _frames
	STA _Ttmp15+1
	LDD _Ttmp14
	STD _Ttmp15
	LDB _Ttmp3
	JSR DSFREE
_linenumber40
```
still no write access to _frames and the code still prints 1 twice.

So I think the code is somewhere else in the compiler. This issue doesn't appear if frames is a simple WORD.

**Comment by spotlessmind1975** [comment]
Fixed.
