### ISSUE TITLE
Avoid multiplication on monodimensional BYTE arrays

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#258]
This code:

         DIM ctab AS BYTE (nums+1)

generates code that makes a multiplication by 1. Maybe CPUMATHMUL16BITTO32BIT can detect this case and return quickly, or better optimize the generator to detect this case and a higher level and avoid the multiplication. This will improve code for all cpus.

Originally posted by @Samuel-DEVULDER in https://github.com/spotlessmind1975/ugbasic/issues/256#issuecomment-979530252_

**Comment by Samuel-DEVULDER** [comment]
Does this code
```
static Variable * calculate_offset_in_array( Environment * _environment, char * _array ) {

    Variable * array = variable_retrieve( _environment, _array );

    if ( array->arrayDimensions != _environment->arrayIndexes[_environment->arrayNestedIndex] ) {
        CRITICAL_ARRAY_SIZE_MISMATCH( _array, array->arrayDimensions, _environment->arrayIndexes[_environment->arrayNestedIndex] );
    }

    Variable * base = variable_temporary( _environment, VT_WORD, "(base in array)");
    Variable * offset = variable_temporary( _environment, VT_WORD, "(offset in array)");

    variable_store( _environment, offset->name, 0 );

    int i,j;

    for( i = 0; i<_environment->arrayIndexes[_environment->arrayNestedIndex]; ++i ) {
		int baseValue = 1;
        for( j=0; j<i; ++j ) {
			baseValue *= array->arrayDimensionsEach[array->arrayDimensions-j-1];
        }
        Variable * index = variable_retrieve( _environment, _environment->arrayIndexesEach[_environment->arrayNestedIndex][array->arrayDimensions-i-1]);
		if(baseValue!=1) {
			variable_store( _environment, base->name, baseValue );
			Variable * additionalOffset = variable_mul( _environment, index->name, base->name );
			variable_add_inplace( _environment, offset->name, additionalOffset->name );
		} else {
			variable_add_inplace( _environment, offset->name, index->name );
		}
    }

    return offset;

}
```
Fixes this issue ?

I think it can be improved even more if one introduces variable_mul_const() which will implement do variable_mul() with a constant multiplier. That routine can check whether the argument is a power of two (eg. (const & -const)==const), and call cpu_math_mul2_const_16bit() or variable_mul() appropriately.



Generally speaking a varianle_mul

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER , **the fix is optimal!**

> I think it can be improved even more if one introduces variable_mul_const() which will implement do variable_mul() with a constant multiplier. That routine can check whether the argument is a power of two (eg. (const & -const)==const), and call cpu_math_mul2_const_16bit() or variable_mul() appropriately.

I did something similar, but using the one-dimensional array case. In this case, it was not necessary to implement the multiplication with constants but I "inverted the operands", thus considering the index as the number to multiply and the shift as the number of bytes.
