### ISSUE TITLE
Invalid index in COLOR(i)

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#275]
https://github.com/spotlessmind1975/ugbasic/blob/2e47ce097ffc45e1df68ad8640c9d31acb078937/ugbc/src/hw/ef936x.c#L207-L208

The index must be a multiple of two. "LSLA" is missing between those two lines. More other the index register is $A7DB and not $A7DA if I'm not mistaken.

**Comment by spotlessmind1975** [comment]
Fixed.
