### ISSUE TITLE
Nothing is printed

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#304]
https://github.com/spotlessmind1975/ugbasic/blob/2b6ba572d704bbd8c3423c2933872fe55aee5b99/examples/arrays_example_01.bas#L12

This example doesn't print anything. The screen remain blank (experienced with PC128 but likely to be present on other platforms).

_Originally posted by @Samuel-DEVULDER in https://github.com/spotlessmind1975/ugbasic/issues/271#issuecomment-996719795_

**Comment by Samuel-DEVULDER** [comment]
Ok I think I have understood why the screen is black for most text example. The root cause seem to be related to
https://github.com/spotlessmind1975/ugbasic/commit/7bb954669f3913f665316a85ab01199c4ff3bdbd

As far as I can tell, the ASM before *_TEXT_AT used to set the value to TEXTPEN. Now TEXTPEN is moved to the global _PEN but nothing in the asm now sets the _PEN value. Consequently text is printed with _PAPER = _PEN = 0, resulting in a blank screen.

Somehow we need to set a default _PEN and _PAPER value either in the startup-code, or in the examples themselves.

**Comment by spotlessmind1975** [comment]
Fixed.

**Comment by Samuel-DEVULDER** [comment]
Cool, thanks. I can now see if I breake anything while recreating opt6809 PR ;)
