### ISSUE TITLE
[pc128op/MO5]Defining a variable with a default value is broken

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#305]
Consider that piece of code:
```
VAR x AS BYTE = 123
PRINT x
```
The generated asm doesn't refer any $7B (123) !

The "_x" value is not set, but only defined by `_x rzb 1` as if its default value was 0, but it should be $7B. I would have expected something like "_x fcb $7B" in that case.

**Comment by Samuel-DEVULDER** [comment]
With version 1.6, the generated asm contained
```
	LDA #$7b
	STA _x
```
which is messing now. This might affect also other global variables like _PEN (see issue #304)

**Comment by spotlessmind1975** [comment]
Fixed.
