### ISSUE TITLE
Is shade 8bits ?

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#307]
https://github.com/spotlessmind1975/ugbasic/blob/802d67b8d0413895d364a0bae11ddedf7dae8d61/ugbc/src/targets/pc128op/color.c#L95

From this code, `shade` is declared as VT_COLOR (like PEN/PAPER, eg 8bits). But according to examples/graphics_color_02.bas , this should be 16bits, hence VT_WORD like in `color_get_vars()`, shouldn't it ?

**Comment by spotlessmind1975** [comment]
Fixed.
