### ISSUE TITLE
problems in release v1.9

### ISSUE THREAD

**Issue by artrag** [spotlessmind1975/ugbasic#322]
The exe files in release v1.9 for msx1 and colecovision do not run on my PC (Windows 10 Pro)
The programs do not start and do not prompt errors. Could it be due to a missing DLL ?
Which DLL have to be installed in order to run ugbasic ?

**Comment by spotlessmind1975** [comment]
**Hello @artrag and thank you for the feedback!**

Can you be kind enough to re-download the executables (from the assets of this repository or via the download button on ugBASIC-IDE) and run it again, giving a sample program with and without embedded compilation? Please, follows the examples you find below. If there are still problems, could you put a snapshot of the output you receive here? Thank you!

Example of program:

     PRINT "hello!"

Command line to execute (pick one):

**MSX**

    ugbc.msx1.exe test.bas -o test.rom
    ugbc.msx1.exe test.bas test.asm

**COLECOVISION**

    ugbc.coleco.exe test.bas -o test.rom
    ugbc.coleco.exe test.bas test.asm

**Comment by spotlessmind1975** [comment]
**Hi @artrag , these are the answers to the rest of your questions:**

> Which DLL have to be installed in order to run ugbasic ?

Every single compiler does not have DLL dependencies.
ugBASIC-IDE depends on .NET 6.0, but a "stand alone" version is present.

**Comment by artrag** [comment]
The coleco version starts but it asks for installing the ZX spectrum tool chain
This is the console  output

C:\Users\Admin\Downloads>ugbc.coleco.exe -I

You have requested to install the chaintool for the ZX Spectrum target.
This implies that "Z88DK - The Development Kit for Z80 Computers"
will be downloaded from the ugBASIC site, and it will be run automatically.
The size of the self-extracting executable is of about 22 MB.n

Do you want to continue [y/N] ?

**Comment by artrag** [comment]
Same story for the msx version. This is the console log

C:\Users\Admin\Downloads>ugbc.msx1.exe test.bas -o test.rom
"\sgbo02.bat" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
The compilation of assembly program failed.

Please use option '-I' to install chain tool.


C:\Users\Admin\Downloads>ugbc.msx1.exe -I

You have requested to install the chaintool for the ZX Spectrum target.
This implies that "Z88DK - The Development Kit for Z80 Computers"
will be downloaded from the ugBASIC site, and it will be run automatically.
The size of the self-extracting executable is of about 22 MB.n

Do you want to continue [y/N] ?

**Comment by artrag** [comment]
If I answer Y I get this other error:
Do you want to continue [y/N] ?y


Downloading: Z88DK - The Development Kit for Z80 Computers

"\sfho0.bat" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
"\sfho01.bat" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
--------------------------------------------------
ugBASIC Compiler v1.9 [target: MSX 1]
--------------------------------------------------
Copyright 2021-2022 Marco Spedaletti (asimov@mclink.it)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this program except in compliance with the License.

usage: ugbc.msx1.exe [options] <source>

Options and parameters:
        <source>     Input filename with ugBASIC source code
        <asm>        Output filename with ASM source code (optional if '-o' given)
        -a           Show statistics on assembly listing generated
        -I           Install needed chaintool for this target
        -d           Enable debugging of IMAGE LOAD
        -p <num>     Maximum number of peep hole optimizations passes (default: 16, 0 = disable)
        -C <file>    Path to compiler
        -A <file>    Path to app maker
        -T <path>    Path to temporary path
        -c <file>    Output filename with linker configuration
        -1           Include source code into the executable
                     and an execution shell. It enforces other.
                     10-liners rules.
        -o <exe>     Output filename with final executable file for target
        -O <type>    Output file format for target:
                        rom - cartridge ROM
        -l <name>    Output filename with list of variables defined
        -e <modules> Embed specified modules instead of inline code
        -L <ignored> Output filename with assembly listing file
        -E           Show stats of embedded modules
        -W           Enable warnings during compilation
        -V           Output version (example: '1.9')

**Comment by spotlessmind1975** [comment]
hello @artrag , and first of all thanks again for taking the time to share the details of the malfunction. 

I'm trying to figure out what's wrong. 

In the meantime, do you have a way to download **[ugBASIC-IDE](https://spotlessmind1975.itch.io/ugbasic-ide)** and try to compile a program with that tool? The advantage is that the ugBASIC-IDE provides the ugBASIC compilers with everything they need to proceed with a compilation, and therefore avoids that (for example) some things are not reachable on the execution path, giving then messages that are not very understandable.

We come to the error messages, and together we try to make a diagnosis.

       C:\Users\Admin\Downloads>ugbc.coleco.exe -I
       You have requested to install the chaintool for the ZX Spectrum target.
       This implies that "Z88DK - The Development Kit for Z80 Computers"
       will be downloaded from the ugBASIC site, and it will be run automatically.
       The size of the self-extracting executable is of about 22 MB.
       Do you want to continue [y/N] ?

Ok, then you have called the compiler with the `-I` option. So you have asked to download in the current directory (then reachable from the ugBASIC compiler) the chaintool that will take care of compiling the result. The fact that the compiler mention `ZX Spectrum target` is a typo, which I will correct at the next bug fixing ( #323 ).

Let's take a look at these error messages:

      "\sfho0.bat" non è riconosciuto come comando interno o esterno,
      un programma eseguibile o un file batch.
      "\sfho01.bat" non è riconosciuto come comando interno o esterno,
      un programma eseguibile o un file batch.

They indicate that the program is unable to generate the script (batch) to download the chain tool (probably a permission issue on the default temporary path). You could create or select a different temporary directory like `c:\Users\Admin\Temp` (or something like that) and then invoke the compiler with these options:

      ugbc.coleco.exe -T c:\Users\Admin\Temp -I

On the question:

      Do you want to continue [y/N] ?

You can go ahead by pressing `y` and waiting for the download to complete. You should find the `z88dk-appmake.exe` and `z88dk-z80asm.exe` programs directly in the same path where you are compiling. From then on you should be able to run the compiler with the `-o` option, and the previously given command line.

Please let me know if there are still any problems.

**Comment by spotlessmind1975** [comment]
Hello @artrag, can we consider the problem solved?

**Comment by spotlessmind1975** [comment]
The problem is considered solved.
