### ISSUE TITLE
Dynamic relocation of 6809 stack

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#346]
In a nutshell, I am finding it difficult to combine the current graphics system (which works on page 0) with a possible additional system, which works on pages 2 and 3. The problem is that the current memory layout of the executable places the stack (at compile time) starting at the address $A000 (downward), which is part of page 3. If I move the stack (at compile time) ) at $2FFF (downward), something changes it in unexpected ways, and therefore causes me problems. At this point I'm playing with the idea of ​​moving it to the address $1FFF, as much video memory would be no longer used... but I can't do it at compile time because, until double buffering is activated, that area is used. So for those who know how to do this... do you have assembly code that dynamically moves the stack from location A ($A000) to location B ($1FFF)? The code should not only set the stack pointer with `LDS` but also copy the current stack so that execution can continue smoothly.

Something like (it's pseudocode and doesn't compile! 🙁):

     LDY # $ A000
     LEAY -S, Y
     TFR Y, U
     LDS # $ 1FFF
     LEAS Y, S
     LDX # $ A000
     LDY # $ 1FFF
     LEA -1, X
     LEA -1, Y
    loop
     LDA, X-
     STA, Y-
     LEAU -1, U
     CMPU # 0
     BNE loop

**Comment by dinoflorenzi** [comment]
pshs x,y,u
 tfr s,x
 pshs x
 ldd oldstack
 subd ,s
 tfr d,u
 ldx oldstack
 lds newstack
loop
 lda ,-x
 pshs a
 leau -1,u
 cmpu #0
 bne loop
 puls x,y,u
 rts
oldstack fdb $5fff       
newstack fdb $4fff

tested OK on PC 128 OLIVETTI PRODEST (MO6)

**Comment by spotlessmind1975** [comment]
Implemented (thank you @dinoflorenzi !).
