### ISSUE TITLE
Refactorizing startup code for SC-3000/SG-1000

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#364]
For SC-3000 / SG-1000 something needs to be fixed: the produced ROM doesn't run on real hardware. It is needed to refactorize the startup code, with the one gently given by Saverio Russo.

**Comment by spotlessmind1975** [comment]
Fixed.

**Comment by mgovoni** [comment]
I will try, as soon as possibile, to burn into a Cartdrige EPROM a program for sega-sc-3000!

**Comment by spotlessmind1975** [comment]
Hi @mgovoni, and **thank you for the feedback!**

Did you obtain a working EPROM?

Thank you again, and have a nice day.

**Comment by mgovoni** [comment]
Hi @spotlessmind1975, I'have just receveid from New Zeland a Sega Megacart (https://sc3000-multicart.com/megacart.htm) I hope to program it as soon as possibile with a ugbasic rom, but I'm going to leave for summer holidays and I think I'll try it in september.
