### ISSUE TITLE
[PC128] [Double Buffer] GET/PUT IMAGE not working

### ISSUE THREAD

**Issue by cttpla** [spotlessmind1975/ugbasic#367]
On PC128, this code doesn't show what's grabbed from screen but instead a square of glitched pixels

    SCREEN #3
    BITMAP ENABLE (160,200,16)
    'Palette
    PALETTE RGB(0,0,0),RGB(255,0,0),RGB(255,255,0),RGB(255,255,0), _
    		RGB(0,0,255),RGB(255,0,255),RGB(0,255,255),RGB(255,255,255), _
    		RGB(187,187,187),RGB(221,119,119),RGB(119,221,119)
    '
    tile1 := LOAD IMAGE("...")
    ' 
    DOUBLE BUFFER ON
    '
    CLS BLACK
    PUT IMAGE tile1 AT 80, 100
    SCREEN SWAP
    PUT IMAGE tile1 AT 80, 100
    SCREEN SWAP
    '
    plrBG := NEW IMAGE(16,16)
    DO
    GET IMAGE plrBG FROM 80, 100
    PUT IMAGE plrBG AT 80, 100
    SCREEN SWAP
    LOOP

**Comment by spotlessmind1975** [comment]
Fixed.
