### ISSUE TITLE
Peephole optimizer 6809: cast from pointer to integer of different size

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#421]
The compilation of the current source presents the following warning for targets with Motorola 6809 processor and active optimization:

    src/targets/d32/_optimizer.c: In function ‘tmp_buf’:
    src/targets/d32/_optimizer.c:224:30: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
      224 |     int hash = tmp_buf_hash(((unsigned int)key1)*31 + key2) % TMP_BUF_POOL;
          |                              ^

The error would appear to be due to the fact that the pointer to the parameter is cast to integer, instead of the value pointed to by the pointer. I ask if @Samuel-DEVULDER could be kind enough to check, and possibly give me confirmation if the fix suggested is correct. Thank you!

**Comment by Samuel-DEVULDER** [comment]
Actually we want to hash the pointer itself, not the value here. The thing is I compile under a 32bit config where integer and pointer share the same size. I think you are working in 64 bits, and the size doesn't match.  

The cast should be unsigned long long for 64bits I guess. 

Adding a variant of the code with #ifdef doesn't look nice. Fortunately [this link](https://stackoverflow.com/questions/21323628/warning-cast-to-from-pointer-from-to-integer-of-different-size ) gives a nice fix. The solution which should work on 32 and 64 bits machines is to simply use `intptr_t` in place of unsigned int according to  "int".

**Comment by spotlessmind1975** [comment]
Fixed.
