### ISSUE TITLE
Optim suggestion.

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#425]
https://github.com/spotlessmind1975/ugbasic/blob/f94f4fd0817fc7b64c1d23527261304ff744e412/ugbc/src/hw/ef936x/startup.asm#L68-L70

`ANDB #$80 / BEQ` can be replaced with a simple BPL (without any ANDB operation) which is much faster.  Later the opposite `ANDB #$80 / BNE` can be replaced with BMI.

**Comment by spotlessmind1975** [comment]
Fixed.
