### ISSUE TITLE
Bank loading on Olivetti PC128 put zero at beginning of block

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#492]
The loading routine from K7, the one that uses the `SWI $20` at startup to load one block at a time and fill the various banks, seems to insert 0s at the beginning of each block. We never noticed it because at most you miss the color on some pixels (and if they are black you don't notice!) - too bad that for `MSC1` a `0` thrown over means "end of stream". 😕

Routine that save banks is here:
https://github.com/spotlessmind1975/ugbasic/blob/main/ugbc/src/targets/pc128op/_cleanup.c

Routine that load banks is here:
https://github.com/spotlessmind1975/ugbasic/blob/main/ugbc/src/hw/pc128op/startup.asm#L106

**Comment by spotlessmind1975** [comment]
Fixed.

**Comment by spotlessmind1975** [comment]
Thanks to @dinoflorenzi for precious suggestion!

**Comment by dinoflorenzi** [comment]
Very little help for a very big project. Always happy to help you😃
