### ISSUE TITLE
Color problem on CPC in mode 1 (320*200 4 colors)

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#525]
With the following code : 
BITMAP ENABLE (320,200,4)
CLS
'Bord noir
COLOR BORDER RGB(0,0,0)	
DRAW 100,100 TO 150,50,RGB(255,0,0)
DRAW TO 200,100,RGB(0,255,0)
DRAW TO 250,50,RGB(0,0,255)

when I compile for CPC 464
I got a red line, a green line and as soon as I draw the blue line, the first line turns blue !
![image](https://user-images.githubusercontent.com/118670680/204050361-ee79235b-54d4-47fe-b28d-1ddaa0ad1045.png)
On an Amstrad CPC in 320*200 mode, you can display 4 colors (1 for the background, and 3 others).
The CPC has a system to manage a palette of 4 inks in mode 1 among a 27 colors palette.
So it shall be possible to make a 3 colors line like this.
![image](https://user-images.githubusercontent.com/118670680/204050701-90133b4d-1dc5-4057-bed0-42f5ef036d3b.png)

**Comment by spotlessmind1975** [comment]
Fixed with commit **6803378f Fixed autoselection color on cpc**.
