### ISSUE TITLE
DRAW doesn't do straight lines !

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#529]
When executing the following code that is intented to draw vertical lines from left to right in sixteen colors on CPC : 

```
BITMAP ENABLE (160,200,16)
'Palette
 PALETTE RGB(255,0,0),RGB(128,0,0),RGB(255,255,0),RGB(255,255,128), _
      RGB(255,128,255),RGB(255,0,255),RGB(0,255,255),RGB(0,255,255), _
      RGB(128,128,128),RGB(255,128,128),RGB(0,0,255),RGB(0,128,255), _
      RGB(128,128,0),RGB(128,255,128),RGB(0,255,0),RGB(0,128,255)
         

 
  FOR x=0 TO 160
  	DRAW x,0 TO x,200,(x MOD 16)
  NEXT	   

```     

I got the following screen 
which indicates clearly that most of the vertical lines have a one pixel shift at the middle of the screen.
That's not very harmfull but I think it's a bug.
I haven't tested on other platforms.

**Comment by ldir-hector** [comment]
![image](https://user-images.githubusercontent.com/118670680/205513455-35fe9a60-4280-4165-a98d-4cf39b31b057.png)

**Comment by ldir-hector** [comment]
If you do lines of only 8 pixels height, they won't be straight neither. I replaced DRAW by BAR and it works, but it's not meant for this !

**Comment by spotlessmind1975** [comment]
The problem has been fixed, and was due to a bad implementation of the 16-bit difference on the Z80 processor, which did not reset the carry before the operation.
