### ISSUE TITLE
Problem with Instruction PALETTE on CPC

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#530]
I have written the following program with the not yet documented instruction PALETTE (I feel like a hacker ! ;) ) 

BITMAP ENABLE (160,200,16)
'Palette
DIM myPalette(16) = #{RGB(255,0,0),RGB(255,0,128),RGB(255,0,255),RGB(255,128,255), _
      RGB(255,128,128),RGB(255,128,0),RGB(255,255,0),RGB(255,255,128), _
      RGB(255,255,255),RGB(128,255,255),RGB(0,255,255),RGB(0,128,255), _
      RGB(0,128,128),RGB(0,0,255),RGB(0,0,128),RGB(0,0,0)}

 PALETTE myPalette(0),myPalette(1),myPalette(2),myPalette(3), _
      myPalette(4),myPalette(5),myPalette(6),myPalette(7), _
      myPalette(8),myPalette(9),myPalette(10),myPalette(11), _
      myPalette(12),myPalette(13),myPalette(14),myPalette(15)
         

 singleBlock := NEW IMAGE(16,8)  	
 doubleBlock := NEW IMAGE(16,16)
 oneColumn := NEW IMAGE(16,200) 
 
  FOR x=0 TO 15
  	BAR x,0 TO x,7,(x MOD 16)
  NEXT	   
 
 GET IMAGE singleBlock FROM  0,0
 
 PUT IMAGE singleBlock AT 0,8      
 WAIT KEY
 GET IMAGE doubleBlock FROM  0,0
 
 FOR i=8 TO 200 STEP 16    
 	PUT IMAGE doubleBlock AT 0,i
 	WAIT KEY
 NEXT    
 
 GET IMAGE oneColumn FROM  0,0
 
```
FOR i=0 TO 160 STEP 16    
 	PUT IMAGE oneColumn AT i,0
NEXT    
'There you can see that not all 16 colors are displayed (i got 4 levels of blue)  
WAIT KEY

decalage=0
WHILE decalage < 200 
	
	      PALETTE myPalette((decalage + 0) MOD 16 ),myPalette((decalage + 1) MOD 16 ),myPalette((decalage + 2) MOD 16 ),myPalette((decalage + 3) MOD 16 ), _
	      myPalette((decalage + 4) MOD 16 ),myPalette((decalage + 5) MOD 16 ),myPalette((decalage + 6) MOD 16 ),myPalette((decalage + 7) MOD 16 ), _
	      myPalette((decalage + 8) MOD 16 ),myPalette((decalage + 9) MOD 16 ),myPalette((decalage + 10) MOD 16 ),myPalette((decalage + 11) MOD 16 ), _
	      myPalette((decalage + 12) MOD 16 ),myPalette((decalage + 13) MOD 16 ),myPalette((decalage + 14) MOD 16 ),myPalette((decalage + 15) MOD 16 )
	      'WAIT VBL
	      WAIT 40 MS
	      
	      		INC decalage
	      
WEND        
'But when the palette is rotating i found the blue !
```

I used WAIT KEY to show some steps, and as I have commented in the source on the first step, we can see that not all 16 colors are displayed !
![image](https://user-images.githubusercontent.com/118670680/205743510-83272f36-1b77-498e-a77b-be1ad739b3a5.png)
I only count 1 dark blue instead of 4 levels of blue !

and then if I press key twice to draw the wall pattern, and once more to initiate the palette rotation, i finally see the blue !
and i got this at the end : 

![image](https://user-images.githubusercontent.com/118670680/205743892-47278ac3-7094-4188-ad48-79fb68c73ae0.png)

Other colors are missing on this screen the two yellows  RGB(255,255,0) and RGB(255,255,128).
I also got some nasty artefact on the screen, but it might be a bug in my code.

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector and **thank you for your bug report!**

At the moment the behavior shown would seem correct: in fact, the color must be given as parameter and not the index. To obtain the desired result, simply replace the line where the bar is drawn with the following:

    BAR x,0 TO x,7,myPalette(x MOD 16)

I suggest you to use `AND` instead of `MOD`, so `x AND 15`, because `MOD` does an integer division. 

Regarding video artifacts, these depend on the fact that a PUT IMAGE is performed with the image going beyond the boundaries of the screen. For efficiency reasons, no runtime checks are performed for screen border crossing.

This is the very same program, without artifacts:

	BITMAP ENABLE (160,200,16)
	'Palette
	DIM myPalette(16) = #{RGB(255,0,0),RGB(255,0,128),RGB(255,0,255),RGB(255,128,255), _
	RGB(255,128,128),RGB(255,128,0),RGB(255,255,0),RGB(255,255,128), _
	RGB(255,255,255),RGB(128,255,255),RGB(0,255,255),RGB(0,128,255), _
	RGB(0,128,128),RGB(0,0,255),RGB(0,0,128),RGB(0,0,0)}
	
	PALETTE myPalette(0),myPalette(1),myPalette(2),myPalette(3), _
	myPalette(4),myPalette(5),myPalette(6),myPalette(7), _
	myPalette(8),myPalette(9),myPalette(10),myPalette(11), _
	myPalette(12),myPalette(13),myPalette(14),myPalette(15)
	
	singleBlock := NEW IMAGE(16,8)
	doubleBlock := NEW IMAGE(16,16)
	oneColumn := NEW IMAGE(16,200)
	
	FOR x=0 TO 15
	   BAR x,0 TO x,7,myPalette(x AND 15)
	NEXT
	
	GET IMAGE singleBlock FROM 0,0
	
	PUT IMAGE singleBlock AT 0,8
	WAIT KEY
	GET IMAGE doubleBlock FROM 0,0
	
	FOR i=IMAGE WIDTH(doubleBlock)\#2 TO (SCREEN HEIGHT-1) STEP IMAGE HEIGHT(doubleBlock)
	   PUT IMAGE doubleBlock AT 0,i
	   WAIT KEY
	NEXT
	
	GET IMAGE oneColumn FROM 0,0
	
	FOR i=0 TO SCREEN WIDTH-1 STEP IMAGE WIDTH(oneColumn)
	 	PUT IMAGE oneColumn AT i,0
	NEXT    
	'There you can see that not all 16 colors are displayed (i got 4 levels of blue)  
	WAIT KEY
	
	decalage=0
	WHILE decalage < 200 
		
		      PALETTE myPalette((decalage + 0) MOD 16 ),myPalette((decalage + 1) MOD 16 ),myPalette((decalage + 2) MOD 16 ),myPalette((decalage + 3) MOD 16 ), _
		      myPalette((decalage + 4) MOD 16 ),myPalette((decalage + 5) MOD 16 ),myPalette((decalage + 6) MOD 16 ),myPalette((decalage + 7) MOD 16 ), _
		      myPalette((decalage + 8) MOD 16 ),myPalette((decalage + 9) MOD 16 ),myPalette((decalage + 10) MOD 16 ),myPalette((decalage + 11) MOD 16 ), _
		      myPalette((decalage + 12) MOD 16 ),myPalette((decalage + 13) MOD 16 ),myPalette((decalage + 14) MOD 16 ),myPalette((decalage + 15) MOD 16 )
		      'WAIT VBL
		      WAIT 40 MS
		      
		      		INC decalage
		      
	WEND        
	'But when the palette is rotating i found the blue !
