### ISSUE TITLE
Second problem with ELLIPSE 

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#532]
I wrote this program to draw 80 concentric ellipses from 1 pixel to 80 pixels height and half of this in width because in mode 0 on CPC pixels are twice wider.
```
BITMAP ENABLE (160,200,16)
CLS
PROCEDURE drawCirclesInMode0

	FOR i=1 TO 80
		ELLIPSE 80,100,(i+1)/2,i
	NEXT
END PROCEDURE

CALL drawCirclesInMode0

```

and i got this weird drawing instead of the full circle I was expecting : 
![image](https://user-images.githubusercontent.com/118670680/206015609-cadc00d7-8238-496e-a505-2dc8cbe945f5.png)

It is the same on MSX (a part from the proportions) : 
![image](https://user-images.githubusercontent.com/118670680/206015678-5cc9ee34-e4a2-4393-be46-45f04a7ef3d3.png)

The funny thing is that it seems to work correctly at the begining. Maybe a problem with too big numbers.

**Comment by ldir-hector** [comment]
I have done another source with palette rotation, it is hypnotic ! 
BITMAP ENABLE (160,200,16)
'Palette
DIM myPalette(16) = #{RGB(255,0,0),RGB(255,0,128),RGB(255,0,255),RGB(255,128,255), _
      RGB(255,128,128),RGB(255,128,0),RGB(255,255,0),RGB(255,255,128), _
      RGB(255,255,255),RGB(128,255,255),RGB(0,255,255),RGB(0,128,255), _
      RGB(0,128,128),RGB(0,0,255),RGB(0,0,128),RGB(0,0,0)}

 PALETTE myPalette(0),myPalette(1),myPalette(2),myPalette(3), _
      myPalette(4),myPalette(5),myPalette(6),myPalette(7), _
      myPalette(8),myPalette(9),myPalette(10),myPalette(11), _
      myPalette(12),myPalette(13),myPalette(14),myPalette(15)

         
PROCEDURE drawCirclesInMode0

	FOR i=1 TO 80
		ELLIPSE 80,100,(i+1)/2,i,myPalette(i MOD 16)
	NEXT
END PROCEDURE
         

PROCEDURE rotationPalette
	decalage=0
	WHILE decalage < 200 
	      PALETTE myPalette((decalage + 0) MOD 16 ),myPalette((decalage + 1) MOD 16 ),myPalette((decalage + 2) MOD 16 ),myPalette((decalage + 3) MOD 16 ), _
	      myPalette((decalage + 4) MOD 16 ),myPalette((decalage + 5) MOD 16 ),myPalette((decalage + 6) MOD 16 ),myPalette((decalage + 7) MOD 16 ), _
	      myPalette((decalage + 8) MOD 16 ),myPalette((decalage + 9) MOD 16 ),myPalette((decalage + 10) MOD 16 ),myPalette((decalage + 11) MOD 16 ), _
	      myPalette((decalage + 12) MOD 16 ),myPalette((decalage + 13) MOD 16 ),myPalette((decalage + 14) MOD 16 ),myPalette((decalage + 15) MOD 16 )
	      WAIT 40 MS
	      INC decalage
     WEND        
END PROCEDURE

CALL drawCirclesInMode0
WAIT KEY
CALL rotationPalette

**Comment by ldir-hector** [comment]
One other detail that puzzled me, if i substitute the for loop with this one :
```

	FOR i=1 TO 40
		ELLIPSE 80,100,i,i*2,myPalette(i MOD 16)
NEXT 
```
I got the same result.
So I made a rather simple test to see if it was a side effect of the loop and with this code : 

```
BITMAP ENABLE (160,200,16)
CLS
```
I got : 
![image](https://user-images.githubusercontent.com/118670680/206259872-7588f1aa-b03d-48fb-832f-b65d2be706c0.png)

**Comment by spotlessmind1975** [comment]
This bug will not be fixed because it is inherent to the type of data representation.
