### ISSUE TITLE
Parasite lines during scroll

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#537]
I have used VSCROLL SCREEN DOWN and tested on CPC and got parasite lines displayed at the top of the screen at the top : 

![image](https://user-images.githubusercontent.com/118670680/208313854-f63280b2-e78a-4913-9cdb-0acd86d519ca.png)

Theses lines remained at the top, flashing. I got the same kind of lines but vertical ones when I used HSCROLL SCREEN LEFT.

My code for the vertical scroll : 
```
BITMAP ENABLE (160,200,16)
CLS
 line2 := LOAD IMAGE("merl1.png")
 line1 := LOAD IMAGE("merl2.png")
 line0 := LOAD IMAGE("merl3.png")
COLOR BORDER RGB(0,0,0)
indexScroll=0
DO	
	IF indexScroll = 0 THEN
						PUT IMAGE line0 AT 0,0:PUT IMAGE line0 AT 64,0
	ELSEIF indexScroll = 1 THEN 
							PUT IMAGE line1 AT 0,0:PUT IMAGE line1 AT 64,0
	ELSEIF indexScroll = 2 THEN 
							PUT IMAGE line2 AT 0,0:PUT IMAGE line2 AT 64,0
	ENDIF
	INC indexScroll : indexScroll = indexScroll MOD 3
	VSCROLL SCREEN DOWN
	VSCROLL SCREEN DOWN
	
LOOP	

```
[water_scroll.cpc.dsk.zip](https://github.com/spotlessmind1975/ugbasic/files/10254429/water_scroll.cpc.dsk.zip)
I also upload the DSK file to show it directly.

**Comment by spotlessmind1975** [comment]
Fixed and release on **COLDFIX v1.12.1 [rev. 20230101.1503]**.
