### ISSUE TITLE
Problem with exponential and negatives

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#542]
I want to draw some parabolic curves so I need to use function like y=x^2.

I do the following code : 

```
BITMAP ENABLE (640,200,2)
CLS

demiLargeur =  -100000
largeur =  70
demiLargeur = largeur /2 
y = -10000
PRINT "demiLargeur ";demiLargeur
FOR x=0 TO largeur
	y= x - demiLargeur
	yCarre=y^2
	PRINT y;" carre ";yCarre;" ";
NEXT
```

I ran it on Amstrad CPC but I got the same problem on MSX.
The result on CPC : 
![image](https://user-images.githubusercontent.com/118670680/211088926-5d40aee8-12fb-4903-b8b4-894f619d6019.png)
As you can see there are two problems : 
- all negative numbers are displayed as positive by PRINT
- all negative numbers raised by power 2 are miscalculated -35 gives 64311 instead of 1225.

The workaround is quite obvious for the second one, I will use ABS function, but it shouldn't be necessary.

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector and thank you for bug reporting.

Both reported issues have been resolved and published with COLDFIX v1.12.1 [rev. 20230107.1540].

See below:
![image](https://user-images.githubusercontent.com/11718606/211156392-0b7d0a27-7bca-46d2-b1cb-f68cefe06d88.png)
