### ISSUE TITLE
Division problem inside a loop

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#543]
I really don't know why I got this bug, because when I try to do the same code as in the issue before and divide by 6 yCarre, the results were all wrong. But when I ask to print directly (32^2)/6 it gives 170 whis is correct !

Here is the code : 

```
BITMAP ENABLE (640,200,2)
CLS
demiLargeur =  -100000
largeur =  70
demiLargeur = largeur /2 
y = -10000
yCarre=(SIGNED 32BIT) 0
PRINT "demiLargeur ";demiLargeur
FOR x=0 TO largeur
	y= (x - demiLargeur)
	yCarre=(y^2)/6
	PRINT "(";y;",";yCarre;") ";
NEXT
PRINT " test ";(32^2)/6

```
The result : 
![image](https://user-images.githubusercontent.com/118670680/211160442-0782d3b3-5995-405a-a28b-35f36d8cc9a2.png)

So theses results can't be used for my pseudo ballistic trajectory.

**Comment by spotlessmind1975** [comment]
Hi @ldir-hector and **thank you for your bug reporting!**

The problem has been fixed on **COLDFIX v1.12.1 [rev. 20230107.2241]**:

![image](https://user-images.githubusercontent.com/11718606/211171526-73c0a35d-3af2-4a6e-89cd-1f831e19553a.png)
