### ISSUE TITLE
MID shall work with variables in both case !

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#548]
If i take the example of MID in the documentation and change it to  : 

```
 a = "ugBASIC"
PRINT "MID(ugBASIC,1) = ";MID(a,2,1)

```
There is nothing displayed, but if I put "ugBasic" as a parameter it works. That's an unfortunate limitation, and it's difficult to understand because when you use MID to modify a String then it works with a variable !

**Comment by spotlessmind1975** [comment]
Hi @ldir-hector and **thank you for your bug reporting!**

It doesn't really have much to do with strings but with a problem generating the Z80 assembly code for comparison. Either way, it's different to use a string or a string variable. They are two very different types of data, and are treated with different codes. The one for string variables had the above bug.

The issue has been fixed on COLDFIX v1.12.1 [rev. 20230111.2012].
