### ISSUE TITLE
HSCROLL SCREEN LEFT doesn't compile on Amstrad CPC

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#549]
I wrote a little program and I got this error message when compiling for the Amstrad CPC : 
![image](https://user-images.githubusercontent.com/118670680/211885331-27a94ed2-3dbc-4bef-bfe3-948d63fd2570.png)
All the other lines compiled well, a part from HSCROLL SCREEN LEFT. Even VSCROLL SCREEN DOWN compiled correctly !

**Comment by spotlessmind1975** [comment]
Hi @ldir-hector and **thank you for your bug reporting!**

The issue has been fixed on COLDFIX v1.12.1 [rev. 20230111.2012].
