### ISSUE TITLE
Problem with >= operator

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#550]
I think >= operator acts as a strict greater than, not like greater or equal : 
The following code : 
```
BITMAP ENABLE
CLS
a=0
PRINT "0 means false";(a>=0)
a=3
PRINT "0 means false";(a>=3)
```
gives this result : 
![image](https://user-images.githubusercontent.com/118670680/212413311-5c35df4a-12b7-4e91-951e-b0376e55470b.png)

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector and **thank your for your bug reporting!**

Fixed on COLDFIX v1.12.1 [rev. 20230114.0948].
