### ISSUE TITLE
Problem with big arrays

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#566]
I was debugging my ballistic program and I couldn't figure what was going on with it.
So I checked all my program, trying to isolate the smaller part that wasn't working right and found that this code where I stored 180 values of Cosinus operation result multiplied by 10000 to workaround the lack of floating numbers had a very bizarre result : 

```
BITMAP ENABLE (640,200,2)
CLS
GLOBAL monCosinus
DIM monCosinus AS SIGNED 32BIT(180) = #{9998,9994,9986,9976,9962,9945,9925,9903,9877,9848,9816,9781,9744,9703,9659,9613,9563,9511,9455,9397,9336,9272,9205,9135,9063,8988,8910,8829,8746,8660,8572,8480,8387,8290,8192,8090,7986,7880,7771,7660,7547,7431,7314,7193,7071,6947,6820,6691,6561,6428,6293,6157,6018,5878,5736,5592,5446,5299,5150,5000,4848,4695,4540,4384,4226,4067,3907,3746,3584,3420,3256,3090,2924,2756,2588,2419,2250,2079,1908,1736,1564,1392,1219,1045,872,698,523,349,175,0,-175,-349,-523,-698,-872,-1045,-1219,-1392,-1564,-1736,-1908,-2079,-2250,-2419,-2588,-2756,-2924,-3090,-3256,-3420,-3584,-3746,-3907,-4067,-4226,-4384,-4540,-4695,-4848,-5000,-5150,-5299,-5446,-5592,-5736,-5878,-6018,-6157,-6293,-6428,-6561,-6691,-6820,-6947,-7071,-7193,-7314,-7431,-7547,-7660,-7771,-7880,-7986,-8090,-8192,-8290,-8387,-8480,-8572,-8660,-8746,-8829,-8910,-8988,-9063,-9135,-9205,-9272,-9336,-9397,-9455,-9511,-9563,-9613,-9659,-9703,-9744,-9781,-9816,-9848,-9877,-9903,-9925,-9945,-9962,-9976,-9986,-9994,-9998,-10000}

angle=(SIGNED 32BIT)45

PRINT "Angle :";angle;" cos(";angle;")=";myCosinus(angle)

```

The result shall be 7193 or 7071 depending if the first array's index is 0 or 1 but instead I got  8224 !
![image](https://user-images.githubusercontent.com/118670680/219479127-9b21756f-172d-4655-b321-f6d802c6cb82.png)
That is completely weird because 8224 isn't even in the array ! All the numbers used are quite small, the SIGNED 32BIT are more than enough to manage them.
So I think there is a problem there !

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector and **thank you for your bug report!**

I have reason to believe that the problem is that you are printing the `myCosinus` array variable while you have defined the `monCosinus` array. Now, the problem is that the program tries to access the 45th element of an array with only ten elements and then it goes to read a memory that doesn't belong to that array. It definitely does not belong to the `monCosinus` variable. If instead of `myCosinus` you use `monCosinus`, the program seems to work as expected (at least, it seems):

    BITMAP ENABLE (640,200,2)
    CLS
    GLOBAL monCosinus
    DIM monCosinus AS SIGNED 32BIT(180) = #{9998,9994,9986,9976,9962,9945,9925,9903,9877,9848,9816,9781,9744,9703,9659,9613,9563,9511,9455,9397,9336,9272,9205,9135,9063,8988,8910,8829,8746,8660,8572,8480,8387,8290,8192,8090,7986,7880,7771,7660,7547,7431,7314,7193,7071,6947,6820,6691,6561,6428,6293,6157,6018,5878,5736,5592,5446,5299,5150,5000,4848,4695,4540,4384,4226,4067,3907,3746,3584,3420,3256,3090,2924,2756,2588,2419,2250,2079,1908,1736,1564,1392,1219,1045,872,698,523,349,175,0,-175,-349,-523,-698,-872,-1045,-1219,-1392,-1564,-1736,-1908,-2079,-2250,-2419,-2588,-2756,-2924,-3090,-3256,-3420,-3584,-3746,-3907,-4067,-4226,-4384,-4540,-4695,-4848,-5000,-5150,-5299,-5446,-5592,-5736,-5878,-6018,-6157,-6293,-6428,-6561,-6691,-6820,-6947,-7071,-7193,-7314,-7431,-7547,-7660,-7771,-7880,-7986,-8090,-8192,-8290,-8387,-8480,-8572,-8660,-8746,-8829,-8910,-8988,-9063,-9135,-9205,-9272,-9336,-9397,-9455,-9511,-9563,-9613,-9659,-9703,-9744,-9781,-9816,-9848,-9877,-9903,-9925,-9945,-9962,-9976,-9986,-9994,-9998,-10000}

    angle=(SIGNED 32BIT)45

    PRINT "Angle :";angle;" cos(";angle;")=";monCosinus(angle)

![image](https://user-images.githubusercontent.com/11718606/219506356-1bd9edcd-6c99-4dc4-b612-ce20eca375f3.png)

**Comment by ldir-hector** [comment]
#FacePalm !
