### ISSUE TITLE
PEEK($C000) doesn't read video memory on CPC

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#574]
I wrote this program :
```
BITMAP ENABLE (640,200,2)
CLS
GLOBAL myPalette
OPTION EXPLICIT
DIM myPalette(2) = #{RGB(0,128,0),RGB(255,255,255)}

PALETTE myPalette(0),myPalette(1)
COLOR BORDER RGB(0,0,0)
PAPER myPalette(0)

PEN myPalette(1)
COLOR BORDER RGB(0,0,0)

FONT LOAD "tank.png" TO 64
VAR i
FOR i=1 TO 640
	PRINT CHR(64);
NEXT
PRINT PEEK($C000);PEEK($C001);PEEK($C002);PEEK($C003);PEEK($C004);PEEK($C005);PEEK($C006);PEEK($C007);
```

I was searching a workaround to know what is displayed on screen. $C000 is by default where the video memory is located on an Amstrad CPC. So I was expecting to see 8 times the number 16 displayed at the bottom after the tank symbol.
But instead I got this : 
![image](https://user-images.githubusercontent.com/118670680/221363760-6ba2776c-42bd-46ff-84a8-a3869d535390.png)

I thaught that maybe, the video ram is on another address, but then I tried the generated DSK on winape and I saw that in C000 and the following addresses, I had 16 ($H10) : 
![image](https://user-images.githubusercontent.com/118670680/221363854-ad73b9a4-d31a-4c7c-a679-560c0d3bd621.png)

So I don't understand what PEEK($C000) is reading and is there a way to read the video memory without breaking the program's execution ?

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector and **thank you for your bug report!**

The problem has been solved but it is not clear to me why you are expecting the value 16. I have run the example and I see all zeros. And that's right because, doing the memory dump, that's the content starting at address $C000.

Anyway, the PEEK behavious has been fixed with COLDFIX v1.13 [rev. 20230226.1336]

**Comment by ldir-hector** [comment]
I was expecting 16 because, if you look at the first line, the first 8 pixels at C000, as we are in Mode 2 (640*200) all theses 8 pixels are all in the same byte, so the 4th pixel wich is the only white one, means that the 1st byte is equal to 16. And so are the next ones as I repeated the same character.
If it was 0, the whole screen shall be green, and I would have seen it within winape debugger too.

**Comment by ldir-hector** [comment]
And it's what I got, thanks !
![image](https://user-images.githubusercontent.com/118670680/221412120-2fb20a80-d683-45fc-8d91-4ad76ed04b2d.png)
