### ISSUE TITLE
UGBasic IDE 1.13.1 - No C64 Compilation Menu

### ISSUE THREAD

**Issue by coderzxy54** [spotlessmind1975/ugbasic#580]
Hello Marco,

I downloaded the latest version UgBasic IDE 1.13.1. When I want to compile an example for the commodore 64, the "_Build/compile/Commodore 64_" menu does no longer exists.

UgBasic IDE 1.13.1 successfully downloaded all updates (latest version of compilers). I checked the C:\Users\%username%\AppData\Roaming\UGBASIC-IDE folder and it's ok

-Computer configuration : Windows 10 x64 22H2
-ugBasic IDE download link: https://spotlessmind1975.itch.io/ugbasic-ide

Cordially,

Coderzxy54

**Comment by spotlessmind1975** [comment]
Hello @coderzxy54 and **thank you for your bug report!**

Indeed there is a bug in the build menu display for Commodore 64. The bug has just been fixed, so you can re-download the IDE executable. If you don't want to redownload the executable, a workaround for the version you're using is to define the path where the VICE emulator is located: this will make the compile menu item reappear.

Thanks again, and happy retrocoding!
