### ISSUE TITLE
Error during compile with latest source from git (coco target)

### ISSUE THREAD

**Issue by mrgw454** [spotlessmind1975/ugbasic#588]
Hello,

Just pulled latest source (to resolve the POINT function) and got the following error when trying to compile with:

make target=coco clean compiler

`make[1]: Entering directory '/home/ron/source/ugbasic/ugbc'
/usr/bin/ld: objs.coco/src/hw/6847.o:(.bss+0x0): multiple definition of `lastUsedSlotInCommonPalette'; objs.coco/src/hw/zx.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [makefile:506: compiler] Error 1
make[1]: Leaving directory '/home/ron/source/ugbasic/ugbc'
make: *** [makefile:235: compiler] Error 2
`
Any help you can provide would be appreciated.  Thank you!

**Comment by spotlessmind1975** [comment]
Hello @mrgw454 and **thank you for your bug report!**

The problem has been fixed with commit cfd2fe0.

I apologize for the inconvenience.

**Comment by mrgw454** [comment]
I'm a big fan of your project.  Thank you for your quick response!

-Ron
