### ISSUE TITLE
Feature Request: C128 (z80 mode without CP/M)

### ISSUE THREAD

**Issue by odflor** [spotlessmind1975/ugbasic#596]
Hi People!

I see that the z88dk is used for generate programs on zx platform.

The z88dk can generate "executables" for c128 using the z80 but on native mode (without using CP/M).

Please date it for next new feature when corresponds.

Best Regards

**Comment by spotlessmind1975** [comment]
Hello @odflor , and **thank you for entering this interesting feature request**

Today I will start the porting process towards the new target, which will be named as `c128z`. I have already updated the [target list](https://ugbasic.iwashere.eu/targets), and I will take care of updating this page to let you know the progress. 

Thank you again, and happy retrocoding!

**Comment by odflor** [comment]
Thank You, very much Mr. Marco!

I promise You that I will use/test the two modes of the c128.

**Comment by spotlessmind1975** [comment]
Added in release 1.14.
