### ISSUE TITLE
PEEK, POKE & SYS

### ISSUE THREAD

**Issue by odflor** [spotlessmind1975/ugbasic#607]
Hi!

Is there a plan to support commands like PEEK, POKE and SYS to allow to fill raw memory areas with bytes, read register status and invoque Assembler programs utilities?

Obviously this kind of programs is platform dependend.

**Comment by spotlessmind1975** [comment]
Hi @odflor , and **thank you for your bug report!**

Coming to your questions, `PEEK` and `POKE` commands are already implemented in ugBASIC, for all platforms. The pages of the manual can be found by clicking here:

https://retroprogramming.iwashere.eu/ugbasic:user:kw:peek
https://retroprogramming.iwashere.eu/ugbasic:user:kw:poke

Regarding the `SYS` command, and more generally the integration of ugBASIC with existing machine code (either preloaded or assembled "on the fly"), there are activities planned on the ROADMAP, and which will come out with a future version. 

These are the issues already present, to which must be added an issue, not yet registered, in which I would like to point out the possibility of supporting calls to machine language routines in a similar way to how Quick Basic does on the Intel platform. That is, using the `DECLARE` statement (or something like that) and then being able to describe how to use the stack and registers during the call.

In particular:

#156
#300
