### ISSUE TITLE
Compile error:  missing sources from "flex" submodule

### ISSUE THREAD

**Issue by mrgw454** [spotlessmind1975/ugbasic#608]
Hello,

Pulled latest source from git and getting the following error for many targets I'm trying to compile:

570:~/source/ugbasic$ make target=coco clean compiler
make[1]: Entering directory '/home/ron/source/ugbasic/ugbc'
make[1]: Leaving directory '/home/ron/source/ugbasic/ugbc'
make[1]: Entering directory '/home/ron/source/ugbasic/ugbc'
make[1]: *** No rule to make target '../modules/flex/src/../src/*.c', needed by '../modules/flex/src/flex'.  Stop.
make[1]: Leaving directory '/home/ron/source/ugbasic/ugbc'
make: *** [makefile:236: compiler] Error 2

I did a recursive pull.  Is there something I'm missing?

Thanks for your help!

**Comment by mrgw454** [comment]
Quick follow-up -- started fresh and just noticed the following error:

x570:~/source/ugbasic$ git submodule update --recursive
fatal: remote error: upload-pack: not our ref 377b2b8e75ea4103ae1496f1f5fe0fbc1e38be10
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'modules/cc65', but it did not contain 377b2b8e75ea4103ae1496f1f5fe0fbc1e38be10. Direct fetching of that commit failed.

**Comment by spotlessmind1975** [comment]
Hi @mrgw454 , and **thank you for the bug report!**

I tried to recursively clone from scratch and rebuild all the modules, and it worked fine for me. 

These are the commands I used:

     git clone https://github.com/spotlessmind1975/ugbasic.git
     cd ugbasic
     git submodule update --recursive --init --remote

Let me know if that resolves it.

**Comment by mrgw454** [comment]
I appreciate the quick response, but still getting an error (using your commands above):

`ron@x570:~/source$ git clone https://github.com/spotlessmind1975/ugbasic.git
Cloning into 'ugbasic'...
remote: Enumerating objects: 39856, done.
remote: Counting objects: 100% (6897/6897), done.
remote: Compressing objects: 100% (1030/1030), done.
remote: Total 39856 (delta 5971), reused 6774 (delta 5848), pack-reused 32959
Receiving objects: 100% (39856/39856), 9.68 MiB | 27.84 MiB/s, done.
Resolving deltas: 100% (33269/33269), done.
ron@x570:~/source$ cd ugbasic
ron@x570:~/source/ugbasic$ git submodule update --recursive --init --remote
Submodule 'modules/asm6809' (https://github.com/mwenge/asm6809.git) registered for path 'modules/asm6809'
Submodule 'modules/bison' (https://github.com/spotlessmind1975/bison) registered for path 'modules/bison'
Submodule 'modules/cc65' (https://github.com/cc65/cc65) registered for path 'modules/cc65'
Submodule 'modules/flex' (https://github.com/spotlessmind1975/flex) registered for path 'modules/flex'
Submodule 'modules/toolshed' (https://github.com/spotlessmind1975/toolshed.git) registered for path 'modules/toolshed'
Submodule 'modules/z88dk' (https://github.com/z88dk/z88dk.git) registered for path 'modules/z88dk'
Cloning into '/home/ron/source/ugbasic/modules/asm6809'...
Cloning into '/home/ron/source/ugbasic/modules/bison'...
Cloning into '/home/ron/source/ugbasic/modules/cc65'...
Cloning into '/home/ron/source/ugbasic/modules/flex'...
Cloning into '/home/ron/source/ugbasic/modules/toolshed'...
Cloning into '/home/ron/source/ugbasic/modules/z88dk'...
Submodule path 'modules/asm6809': checked out '69036d35f28d486ef9bcdbe9b0acb9af3885a63c'
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'modules/bison'
`

Perhaps I'm still missing something obvious?  Thanks again for your help!

**Comment by spotlessmind1975** [comment]
Hello @mrgw454 , maybe I figured out what the problem is: I have the impression that git is looking for the `master` branch but there is no such branch, since the new standard on github is `main`. Now I do some operations and let you know as soon as I fix the repository. Thank you again for your patience!

**Comment by spotlessmind1975** [comment]
Hello @mrgw454 , could you be so kind as to try again now? Thank you!

**Comment by spotlessmind1975** [comment]
Sorry @mrgw454 there are problems, yut. Please be patient.

**Comment by mrgw454** [comment]
I was just trying it out and, so far, a few targets are compiling fine
(like coco).  I will wait for your update, though.

Thanks for getting me to this point.  :)

-Ron

**Comment by spotlessmind1975** [comment]
Ok @mrgw454 now it should work! 👍

**Comment by mrgw454** [comment]
It's all working now -- thank you so much!
