### ISSUE TITLE
Keyboard rate and delay parameter configuration

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#625]
It is suggested to implement a mechanism for tuning and configuring keyboard behavior. In particular, a parameter should be used to specifies the rate at which character output from a keyboard repeats, in characters per time unit, after a key is pressed and continuously held down. Moreover, another parameter must specify the amount of time that must elapse after a key is pressed and continuously held down, before the character output from a keyboard begins to repeat.

**Comment by pwillard** [comment]
Looking forward to this... thank you for considering.

**Comment by spotlessmind1975** [comment]
Hello @pwillard , and **thank you for your comment!**

I'm proceeding to implement the two new ugBASIC commands for the various targets:

    DEFINE KEYBOARD RATE xx
    DEFINE KEYBOARD DELAY xx

As soon as they are ready, it will be my care to report it here.

Thank you again and happy retrocoding!

**Comment by pwillard** [comment]
That should work nicely...

Grazie mille

**Comment by spotlessmind1975** [comment]
Fully implemented on COLDFIX v1.14.1 [rev. 20230720.0046].

Manual pages:
https://retroprogramming.iwashere.eu/ugbasic:user:kw:define_keyboard_delay
https://retroprogramming.iwashere.eu/ugbasic:user:kw:define_keyboard_rate
