### ISSUE TITLE
Error on new ide version

### ISSUE THREAD

**Issue by odflor** [spotlessmind1975/ugbasic#631]
The last version of https://spotlessmind1975.itch.io/ugbasic-ide, has errors when is executed.

![imagen](https://github.com/spotlessmind1975/ugbasic/assets/25032803/9c52effc-4a89-4c7c-a52e-88e2968845b3)

And nothing works.

**Comment by spotlessmind1975** [comment]
Hello @odflor and **thank you for your bug report!**

Could you be so kind as to send me the command sequence to replicate the problem? 
If possible also the contents of the Details button. 

**Thank you again!**

**Comment by odflor** [comment]
Just need to try to open a existing file.

Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

************** Texto de la excepción **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ugbasic_ide.CompilersConfigurationData.getProperty(String _target)
   at ugbasic_ide.Common.canCompile(String _target)
   at ugbasic_ide.Common.UpdateCompilerMenu(Editor _editor)
   at ugbasic_ide.Editor.Editor_GotFocus(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnGotFocus(EventArgs e)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WmSetFocus(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Ensamblados cargados **************
System.Private.CoreLib
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
ugbasic-ide
    Versión del ensamblado: 1.14.1.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 6.0.2.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.ComponentModel.Primitives
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Runtime
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Windows.Forms.Primitives
    Versión del ensamblado: 6.0.2.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Runtime.InteropServices
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Drawing.Primitives
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Collections.Specialized
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
Microsoft.VisualBasic.Forms
    Versión del ensamblado: 6.0.2.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Drawing.Common
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Diagnostics.TraceSource
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Collections
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
Microsoft.Win32.Primitives
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Threading
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Threading.Thread
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
Accessibility
    Versión del ensamblado: 4.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.ComponentModel.TypeConverter
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
Microsoft.Win32.SystemEvents
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Collections.Concurrent
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.ComponentModel
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Numerics.Vectors
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Memory
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Resources.Extensions
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Drawing
    Versión del ensamblado: 6.0.2.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.ObjectModel
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Linq
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Runtime.Loader
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 6.0.2.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Collections.NonGeneric
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Xml.ReaderWriter
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Private.Xml
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
Microsoft.VisualBasic.Core
    Versión del ensamblado: 11.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Xml.XmlSerializer
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Text.Encoding.Extensions
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Text.RegularExpressions
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Reflection.Emit.ILGeneration
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Reflection.Emit
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
Microsoft.GeneratedCode
    Versión del ensamblado: 1.0.0.0
    Versión Win32: N/D
    Código base: file:///D:/Downloads/commodore_stuff/ugBasic/System.Private.Xml.dll
----------------------------------------
System.Reflection.Primitives
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
Microsoft.GeneratedCode
    Versión del ensamblado: 1.0.0.0
    Versión Win32: N/D
    Código base: file:///D:/Downloads/commodore_stuff/ugBasic/System.Private.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Versión del ensamblado: 1.0.0.0
    Versión Win32: N/D
    Código base: file:///D:/Downloads/commodore_stuff/ugBasic/System.Private.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Versión del ensamblado: 1.0.0.0
    Versión Win32: N/D
    Código base: file:///D:/Downloads/commodore_stuff/ugBasic/System.Private.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Versión del ensamblado: 1.0.0.0
    Versión Win32: N/D
    Código base: file:///D:/Downloads/commodore_stuff/ugBasic/System.Private.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Versión del ensamblado: 1.0.0.0
    Versión Win32: N/D
    Código base: file:///D:/Downloads/commodore_stuff/ugBasic/System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Net.Requests
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Private.Uri
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Net.Primitives
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Net.WebHeaderCollection
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Net.Http
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Diagnostics.Tracing
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Net.ServicePoint
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Net.Security
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Security.Cryptography.X509Certificates
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Diagnostics.DiagnosticSource
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Net.Sockets
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Net.NameResolution
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Security.Cryptography.Primitives
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Security.Principal.Windows
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Security.Claims
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Threading.Overlapped
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Threading.ThreadPool
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Security.Cryptography.Encoding
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Linq.Expressions
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
Alsing.SyntaxBox
    Versión del ensamblado: 2.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Resources.ResourceManager
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Web.HttpUtility
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Runtime.Extensions
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Runtime.Serialization.Formatters
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Reflection.Emit.Lightweight
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Diagnostics.StackTrace
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Reflection.Metadata
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------
System.Collections.Immutable
    Versión del ensamblado: 6.0.0.0
    Versión Win32: N/D
    Código base: 
----------------------------------------

************** Depuración JIT **************

**Comment by spotlessmind1975** [comment]
Hi @odflor, **thank your for the feedback!**

I specifically couldn't reproduce the problem, however I have made a fix that should fix it. Please be kind enough to download the IDE again, and repeat the procedure, to verify that the problem is resolved.

**Comment by odflor** [comment]
Now is working!

Thanks a lot!

Best Regards

**Comment by spotlessmind1975** [comment]
**Thank you @odflor for your kind feedback!**
