### ISSUE TITLE
Permission Denied Error

### ISSUE THREAD

**Issue by pwillard** [spotlessmind1975/ugbasic#635]
A program containing only 1 print statement.

PRINT "TEST"

COMPILE:   GET ERROR -> cannot remove file: d:\dev\basic\test1.bas, Permission Denied

Started happening only after installing the latest IDE.
![Capture](https://github.com/spotlessmind1975/ugbasic/assets/3194144/5a215d5f-76ef-403e-8585-9b5f31a0ed53)

**Comment by pwillard** [comment]
I did a full removal and re-installation of the IDE software and related files... the same issue remains when I open *that*  or similar *existing* files I created. There are no special permissions on folders or files that I can see.  The issue stays with the FILE even if I move it.

I could not duplicate the issue if I create *new* output files in the same folder, for example.  So I'm perplexed about why I get the error with the *existing* source file even with some other folders I tried.
![Capture2](https://github.com/spotlessmind1975/ugbasic/assets/3194144/f5a2fed6-dff6-4cf9-8d20-2b98b8eec29d)

**Comment by spotlessmind1975** [comment]
Hello @pwillard and **thank you foir your bug report!**

The only thing I note as strange is that Windows shouldn't allow saving files under the `C:\Programs` directory, which is a directory dedicated to applications. Have you tried moving the source to an unprotected directory, like `C:\DEV` or something like that?

Let me know. Thank you!

**Comment by pwillard** [comment]
Even if I use 2 files from the same folder.  "c:\programs\xroar\dev"   If I open the file saved last week... I get the error.  If I use a file I just created... it's OK.  They have the SAME contents.  Since these are  ASCII TEXT FILES and Windows says that it is NOT READ-ONLY, then I have no idea why it says Permission denied on the older existing files.

**Comment by spotlessmind1975** [comment]
Hi @pwillard , and **thank you for your feedback!**

Microsoft Windows has a special feature, called "Microsoft Defender SmartScreen", that can change the behaviour of the programs. It is specially true if an executable is updated and you are referring to a special path like the `c:\programs`. Unfortunately, there is nothing I can do about this behaviour.

Did you try from another folder, different from a subfolder of `c:\programs`?

**Comment by pwillard** [comment]
Yes, I have tried multiple folders.

PLEASE NOTE:  `c:\programs` is MY folder... it is not created or managed by Windows SYSTEM like `Program Files` is.

**Comment by spotlessmind1975** [comment]
Hi @pwillard , and **thank you for your kind feedback.**

Let's try to see if we can gather more information on the command line issued by the IDE, and check if there are anomalies. 

![image](https://github.com/spotlessmind1975/ugbasic/assets/11718606/20c3f2ef-eba9-4110-bcec-185ef23f7bf4)

Go to the right bottom angle of the editor window, and select "additional info".

![image](https://github.com/spotlessmind1975/ugbasic/assets/11718606/e0d7abcf-cc04-4b9c-a2f0-e9e39bc0d4f1)

At this point compile the program for the indicated target, for the file where you are successful. A new window should appear. 
 Select the "Command line" tab. 

![image](https://github.com/spotlessmind1975/ugbasic/assets/11718606/f16ee70a-9d76-4560-aef5-eba1f6dd9a37)

Take the contents of the text box and put it here. Let's see if there are elements that can help us understand why the compiler gives that error.

**Comment by pwillard** [comment]
C:\Users\willard\AppData\Roaming\UGBASIC-IDE\ugbc.coco.exe  -O dsk -C
"C:\Users\willard\AppData\Roaming\UGBASIC-IDE\asm6809.exe" -b
"C:\Users\willard\AppData\Roaming\UGBASIC-IDE\decb.exe" -L
"C:\Programs\xroar\DEV\NewTest.listing" -i
"C:\Users\willard\AppData\Roaming\UGBASIC-IDE\imports" -T
"C:\Users\willard\AppData\Roaming\UGBASIC-IDE\temp" -D
"C:\Users\willard\AppData\Roaming\UGBASIC-IDE\temp\NewTest.info" -p 16 -o
"C:\Programs\xroar\DEV\NewTest.coco.dsk" "C:\Programs\xroar\DEV\NewTest.bas"

**Comment by spotlessmind1975** [comment]
Hi @pwillard , **thank you again for the additional info**.

Thanks to the information you kindly provided me, I think I've managed to identify the problem, which could be related to Windows, and a specific issue of the file system. I applied a fix on the IDE that should prevent the problem from happening again. 

You should be kind enough to download the IDE again and repeat the procedure. If I've figured out the problem, you should no longer get the "permission denied" error. Let me know.

The updated IDE can be downloaded from here:
https://spotlessmind1975.itch.io/ugbasic-ide

**Comment by pwillard** [comment]
Unlike before... Windows now sees ugbc.coco.exe as a virus and quarantined
it...

So now I get:
[image: Capture1.PNG]

**Comment by pwillard** [comment]
I told Windows AntiVirus to ALLOW ugbc.coco.exe (even though it insists that it is: Trojan:Win32/Bearfoos.A!ml )  and this is the result from COMAMND LINE: C:\Users\willard\AppData\Roaming\UGBASIC-IDE\ugbc.coco.exe  -O dsk -C "C:\Users\willard\AppData\Roaming\UGBASIC-IDE\asm6809.exe" -b "C:\Users\willard\AppData\Roaming\UGBASIC-IDE\decb.exe" -L "C:\Programs\xroar\DEV\NewTest.listing" -i "C:\Users\willard\AppData\Roaming\UGBASIC-IDE\imports" -T "C:\Users\willard\AppData\Roaming\UGBASIC-IDE\temp" -D "C:\Users\willard\AppData\Roaming\UGBASIC-IDE\temp\NewTest.info" -p 16 -o "C:\Programs\xroar\DEV\NewTest.coco.dsk" "C:\Programs\xroar\DEV\NewTest.bas"

**Comment by spotlessmind1975** [comment]
Ok @pwillard but... it works now?

**Comment by pwillard** [comment]
once I allow it and say the compiler is not EVIL... yes, I can open the OLD
file that failed and it will compile with no error now.

**Comment by spotlessmind1975** [comment]
So we can close the bug.

Since IDE download the **ugbc.coco.exe** from a safe source (official website), it is a false positive for sure. Using Microsoft Widnows it happens, unfortunately. Every executable is compiled "from scratch" from sources, and you could do it by yourself using repository, so really there is no way to add a trojan. Moreover, I've checked the file using VirusTotal [see below] and none of them show a virus using 60+ different engines. 

There's not much on my side I can do to prevent that. Most AV tools allow you to submit a false positive once it was verified that no other engine or most other engines do not detect anything. Not sure if you AV has something like that but on my machine, it doesn't flag any of these files. You may check the checksums of the files to verify the file version is the same.

https://www.virustotal.com/gui/file/c215af89cd7348ec95ad8bc3ed7d098b45e6ef8edcae64e649c26d29f1bf9d91/detection

![image](https://github.com/spotlessmind1975/ugbasic/assets/11718606/12817441-71ed-45ce-8759-65bd2ed05913)
