### ISSUE TITLE
IDE Feature Request c128z

### ISSUE THREAD

**Issue by odflor** [spotlessmind1975/ugbasic#639]
Hi:

When is possible.

Start VICE (x128.exe) with "-80col" parameter for target c128z, because c128z target is for 80 columns only.

Best Regards

**Comment by spotlessmind1975** [comment]
Hi @odflor , and **thank you for your kind suggestion!**

I'm proceeding with the implementation and, as soon as I'm done, I'll report it on this ticket.

Thank you again, and have a nice retrocoding!

**Comment by spotlessmind1975** [comment]
Hi @odflor , the feature was implemented with the latest published version of the IDE. 
You should download again the IDE from itch.io again. 
Thank you very much, and have a nice retrocoding!
