### ISSUE TITLE
VIC 20 don't show graphics

### ISSUE THREAD

**Issue by odflor** [spotlessmind1975/ugbasic#651]
The VIC 20 can't show this program.

![imagen](https://github.com/spotlessmind1975/ugbasic/assets/25032803/d27174f9-216f-4f04-b530-dbf35725ff71)

![imagen](https://github.com/spotlessmind1975/ugbasic/assets/25032803/111c7a37-e8b1-4de9-bc5a-cbddfd6f38e6)

**Comment by odflor** [comment]
A emulation of graphics mode con VIC 20 could by made further.

**Comment by spotlessmind1975** [comment]
Hi @odflor, **first of all thank you for your bug report!**

Have you try this example? 

[What a Wonderful World](https://github.com/spotlessmind1975/ugbasic/blob/main/examples/contrib_what_a_wonderful_world.bas)

It uses graphics and it works on `vic20`.

Thank you again, and have a nice retrocoding!
