### ISSUE TITLE
Problem using WAIT KEY on target c128 and c128z

### ISSUE THREAD

**Issue by odflor** [spotlessmind1975/ugbasic#654]
CLS
     PRINT "PLEASE PRESS A KEY"
     WAIT KEY
     PRINT "THANK YOU!"

WAIT KEY don't stop and wait to the user to press a key.

Best Regards

**Comment by spotlessmind1975** [comment]
Hi @odflor and **thank you for your bug report!**

I just checked with the current `main` version (the one that can be downloaded from the [dedicated page](https://ugbasic.iwashere.eu/install) or using the IDE), and it seems to me that the `WAIT KEY` command works correctly in both targets (`c128` and `c128z`). I used the `controls_keyboard_08` example for this (see below). If you have a different example source that with the current version shows the problem, please put it here that I will elaborate further.

Thank you again, and have a nice day!

`c128`
![image](https://github.com/spotlessmind1975/ugbasic/assets/11718606/3acd14d6-137d-46e5-803f-aeedc9432919)

`c128z`
![image](https://github.com/spotlessmind1975/ugbasic/assets/11718606/f090c0fc-e1ae-4c35-b5e2-5da735d4d912)
