### ISSUE TITLE
Problem with RND and variable

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#659]
I have tested this with both Normal and Beta compiler on CPC and MSX.

The code is simple : 
```
BITMAP ENABLE(640,200,2)
VAR temp AS INTEGER
RANDOMIZE TIMER
CLS

FOR i=1 TO 640
	temp = 400
	PRINT RND(temp);" ";RND(400)
NEXT
```
The result for RND(temp) is always 0 while RND(400) is working as expected.
So there is something not working with parameters that are stored in a variable.

**Comment by spotlessmind1975** [comment]
Hi @ldir-hector, and **thank you for your bug report!**

The problem for `cpc` has been fixed with COLDFIX v1.14.1 [rev. 20230908.2254].

The problem for `msx1` should be already fixed with the latest version.

Let me know if the issues has been resolved.

**Comment by ldir-hector** [comment]
Thanks a lot, it works on both compilers !

**Comment by ldir-hector** [comment]
I have made a mistake, in fact it's working only on the normal compiler, not in the beta.

**Comment by spotlessmind1975** [comment]
Hi @ldir-hector, first of all thank you for your feedback. To be honest, I thought you meant for `cpc` and for `msx1`. Infact, to publish the fix more quickly, it was published only in the `main` version. To avoid a double download, I wrote it in the announcement on the Facebook group (Version: main). I'm very sorry for making you download the compiler twice! Next time I'll try to say it better. Thank you very much, anyway!

**Comment by ldir-hector** [comment]
Hi @spotlessmind1975 
It's not a problem for me to test on both compilers, I got optic fiber and an infinite data contract !
In fact, I'm not even sure I need the beta compiler for my project. 
I didn't work much on it during this summer because it was damn hot here and I hate that ! I hope i will go back to this in a few days.
