### ISSUE TITLE
Add support for keyword CENTER AT (TSB only)

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#814]
Syntax:

     CENTER [ AT(zl,sp) ] <string> | <strvar> [, <width>]

`CENTER` / `CENTRE` outputs strings or the contents of string variables centered on the screen. The cursor remains behind the output (as with `PRINT` with a semicolon) or not, based on pragma. 

If not specified otherwise by the optional `AT(zl,sp)`, the output is on the screen line on which the cursor is currently located and, without the `<width>` parameter, refers to the full line width of 40 characters (or the characters of console).  If the cursor is not positioned at column 0 but somewhere within the screen line, the remaining width (40 minus `POS(0)` ) is used as the centering basis.

The optional `<width>` parameter specifies which value should be used as the basis for centering. The indentation is therefore carried out with reference to this specification ( (`<width>` minus `LEN(<string>)`) divided by 2 ).

If the result of the internal indentation calculation is `0` or less than `LEN(<string>)` plus 2, no indentation is performed. The value `<width>` can be greater than 40 (maximum 255), but no more indentation occurs if the calculation result is `LEN(<string>)` plus 128 (internally results in a negative byte value). 

If the first parameter is not an expression of type string, the error message `TYPE MISMATCH ERROR` is displayed. If the first parameter is missing or more than two are specified, the program is aborted with `SYNTAX ERROR`. 

If the second parameter is less than 0 or greater than 255, an `ILLEGAL QUANTITY ERROR` is displayed. 

Example: 

    10 CLS: CENTER “demo” 
    20 PRINT AT(2,0) DUP(“*”,40) 
    30 PRINT AT(4,0) “Stop by C=” AT(5,0) “Slow by CTRL” AT(6,0) “Break by STOP” 
    40 PRINT AT(8,0) DUP(“{shift-*}”, 40) 
    50 FOR i=1 to 5: PRINT AT(1 0+i,4)"-" AT(10+i,14) "-" AT(10+i,24) "-" AT(10+i,34) "-"
    60 NEXT 
    70 FOR i=0 to 2 
    80 CENTER AT(11,5+i*10) "No."+str$(i+1),9
    90 NEXT: PRINT AT(20,0) ""; 

Outputs a centered overall heading (line 10), a few info lines (lines 20 to 40) and an (empty) table (lines 50 and 60) with centered headings (especially in line 80)

**Comment by godot64** [comment]
Line 80 should read 

80 CENTER AT(11,5+i*10) "No.";str$(i+1),9

correctly ("width" gets separated by a comma not by a semicolon)

Arndt
