### ISSUE TITLE
Add support for keyword CGOTO (SB)

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#816]
Calculate the number of the line to which the program execution must pass. Allows you to jump to a variable program line number, determined by the result of a calculation. `CGOTO` is a command that replaces long jump tables behind the BASIC command `ON`. Instead of specifying the jump targets as with `ON` and then calling them by specifying the location number of the desired target, the desired target line can be targeted immediately by calculation after `CGOTO` without much typing. The use of `CGOTO` requires that the lines are arranged in such a way when programming that these lines remain accessible for the algorithm `<expression>` behind `CGOTO`. Since Simons' Basic is designed to do without line numbers anyway (see `EXEC` and `PROC`), the usefulness of `CGOTO` is rather doubtful.

**Comment by godot64** [comment]
Since CGOTO is made for line numbers, would it be a useful addition to ugBasic?
