### ISSUE TITLE
Add support for keyword EXEC (SB+TSB only)

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#840]
Syntax:

    EXEC <label>

In TSB, just like in Simons' Basic, subroutines can be given a name (see `PROC`). This makes them independent of their position in the program and makes it easier for the programmer to keep track of things (names are easier to assign to a purpose than line numbers). The `EXEC` command calls such a subroutine, processes it and returns to its starting point. It is therefore largely equivalent to the BASIC V2 command `GOSUB`.  This is not the ugBASIC semantic.

So ugBASIC should support a pragma to define the semantic for `EXEC` keyword.

     OPTION EXEC AS GOTO: REM ugBASIC meaning (default)
     OPTION EXEC AS GOSUB: REM SB+TSB meaning

Unlike in Simons' Basic and TSB, the EXEC keyword canno be omitted. In addition, any other BASIC commands can follow a colon after the label in the line in which a procedure call is used. TSB-EXEC also ignores a space at the beginning of a label (the possible gap between `PROC` and the label name as in the example below). Procedure calls can therefore be handled much more flexibly than under Simons' Basic.

The processing speed of `EXEC` and `CALL` is much slower under Simons' Basic than with the comparable commands `GOSUB` and `GOTO` in Basic V2, because all characters of the label must be compared when searching for the jump destination. To compensate for this disadvantage, TSB creates a table of all `PROC` addresses (starting at address `$C400`) during program execution and first looks for `PROCs` in this table (see `CHECK`). The processing speed of a program with many procedures is thus significantly increased during operation and is faster than Basic V2.

If the label behind `EXEC` is not found in the program, the error message `NO PROC ERROR` appears. If a TSB program encounters an end of procedure (`END PROC`) without having called a procedure, the message `END PROC W/O EXEC ERROR` appears. If there are too many nestings (more than ten), TSB reports an `OVERFLOW ERROR`.

**Comment by godot64** [comment]
Is there any way to deal with the fact that you can omit the EXEC keyword (so that just `label `works just like `EXEC label`)?

Arndt
