### ISSUE TITLE
Add support for keyword HIRES (SB)

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#849]
Syntax:

    HIRES <ink>, <paper>

`HIRES` is used to switch the C64 from text to high-resolution graphics mode (320×200 pixels) and to use the specified colors: `<ink>` for the writing color and `<paper>` for the background color (both with values ​​from 0 to 15). The graphics memory (at address $E000) is deleted and preset with the specified colors. The color memory for hires images is located in Simons' Basic at address $C000. The color of the screen frame remains unaffected. In direct mode, Simons' Basic immediately jumps back to text mode after executing the command. In a program, the selected mode remains active until it is switched off or changed by a command (`MULTI`, `CSET` or `NRM`).

Important: The color specifications of almost all other graphics commands refer to the colors specified here. If the color source "0" is specified in a graphics command, the color specified for `<paper>` is selected; if "1" is specified, the color for `<ink>` is selected; the color specification "2" inverts the controlled pixel (if in hires mode, otherwise see `MULTI`).

If no parameter is entered, the error message `SYNTAX ERROR` appears; if the value is incorrect, `BAD MODE ERROR` appears.

**Comment by godot64** [comment]
MULTI doesn't switch off the graphics screen but only changes the screen mode to multicolor. At the same time the colors specified by HIRES get replaced by the colors behind MULTI, where parameter 1 replaces "ink" and parameter 2 replaces "paper" (parameter 3 changes the color ram area at $d800).

Arndt
