### ISSUE TITLE
Already present keyword JOY (SB+TSB only)

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#854]
On TSB `JOY` reads the value of one of the two C64 control ports (CIA 1, $DC00 and $DC01) in order to make a joystick connected there usable for the program. The values ​​that the port supplies are translated into values ​​between 0 and 8, with each value being assigned to a specific direction. When the fire button is pressed, a value of 128 is added to the direction value. **This is not the ugBASIC convention.** So we need a pragma to change the kind of value returned by `JOY` function.

    DEFINE JOYSTICK VALUES DEFAULT : REM Enable values as ugBASIC
    DEFINE JOYSTICK VALUES TSB : REM Enable values as TSB

**Comment by godot64** [comment]
Also, TSB can address either one of the two ports by adding their number in parenthesis: a=joy(2) giving the value a from port 2. The value of 0 is returned when the joystick is not in use.

Arndt
